"""
ApplicationPdfService — Phase 159.

Renders a single application as a self-contained PDF the NGO can keep
on file. Audit-folder ZIP (Phase 73) is the right artifact when you
need the whole bundle; this is for the case where the NGO just wants
their own application document.

Layout:
  - Header: grant title + NGO name + status pill + submitted date
  - Section per criterion: label + response (preserving line breaks)
  - Budget summary if present
  - Footer on every page with metadata + Kuja attribution
"""

from __future__ import annotations
import io
import logging

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table,
    TableStyle, PageBreak,
)

logger = logging.getLogger('kuja')

KUJA_CLAY = colors.HexColor('#a55636')
KUJA_INK = colors.HexColor('#1f2937')
KUJA_MUTED = colors.HexColor('#6b7280')


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(KUJA_MUTED)
    canvas.setFont('Helvetica', 8)
    text = f'Page {canvas.getPageNumber()} · Generated by Kuja'
    canvas.drawRightString(A4[0] - 15 * mm, 12 * mm, text)
    canvas.restoreState()


def build_application_pdf(*, application, grant, org, criteria: list[dict],
                          responses: dict) -> bytes:
    """Return PDF bytes for one application."""
    buf = io.BytesIO()
    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=f'Application — {application.id}',
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id='body',
    )
    doc.addPageTemplates([PageTemplate(id='main', frames=[frame], onPage=_footer)])

    styles = {
        'h1': ParagraphStyle(
            'h1', fontName='Helvetica-Bold', fontSize=18,
            textColor=KUJA_CLAY, spaceAfter=4,
        ),
        'h2': ParagraphStyle(
            'h2', fontName='Helvetica-Bold', fontSize=13,
            textColor=KUJA_INK, spaceBefore=10, spaceAfter=4,
        ),
        'meta': ParagraphStyle(
            'meta', fontName='Helvetica', fontSize=9,
            textColor=KUJA_MUTED, spaceAfter=2,
        ),
        'body': ParagraphStyle(
            'body', fontName='Helvetica', fontSize=10,
            textColor=KUJA_INK, leading=14, spaceAfter=4,
        ),
        'small': ParagraphStyle(
            'small', fontName='Helvetica-Oblique', fontSize=8,
            textColor=KUJA_MUTED, spaceAfter=2,
        ),
    }

    flow = []
    grant_title = (grant.title if grant else f'Grant #{application.grant_id}')
    org_name = (org.name if org else f'Org #{application.ngo_org_id}')

    flow.append(Paragraph(f'<b>{_escape(grant_title)}</b>', styles['h1']))
    flow.append(Paragraph(f'Application by {_escape(org_name)}', styles['meta']))
    flow.append(Paragraph(
        f"Application #{application.id} · status: {application.status} · "
        f"submitted: "
        f"{application.submitted_at.strftime('%Y-%m-%d') if application.submitted_at else '—'}",
        styles['meta'],
    ))
    flow.append(Spacer(1, 6))

    if not criteria:
        flow.append(Paragraph('No proposal criteria defined.', styles['body']))
    else:
        for c in criteria:
            key = c.get('key') or ''
            label = c.get('label') or key
            response_text = (responses.get(key) or '').strip() or '— No response —'
            flow.append(Paragraph(_escape(label), styles['h2']))
            for para in response_text.split('\n\n'):
                if not para.strip():
                    continue
                flow.append(Paragraph(_escape(para).replace('\n', '<br/>'), styles['body']))

    # Budget summary
    try:
        budget_lines = application.get_budget_lines() if hasattr(application, 'get_budget_lines') else []
    except Exception:
        budget_lines = []
    if budget_lines:
        flow.append(PageBreak())
        flow.append(Paragraph('Budget', styles['h1']))
        rows = [['Item', 'Category', 'Amount']]
        total = 0.0
        for bl in budget_lines:
            label = str(bl.get('label') or bl.get('name') or '—')
            category = str(bl.get('category') or '—')
            amount = bl.get('amount') or bl.get('value') or 0
            try:
                total += float(amount)
            except (TypeError, ValueError):
                pass
            rows.append([
                _escape(label[:60]),
                _escape(category[:30]),
                f'{float(amount):,.0f}' if amount else '—',
            ])
        rows.append(['', '<b>Total</b>', f'<b>{total:,.0f}</b>'])
        tbl = Table(rows, colWidths=[None, 50 * mm, 30 * mm])
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), KUJA_CLAY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 9),
            ('FONT', (0, 1), (-1, -1), 'Helvetica', 9),
            ('GRID', (0, 0), (-1, -1), 0.25, KUJA_MUTED),
            ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#fef7f0')]),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#fef7f0')),
        ]))
        flow.append(tbl)

    doc.build(flow)
    return buf.getvalue()


def _escape(s: str) -> str:
    import html as _h
    return _h.escape(s or '', quote=False)
