"""
Phase 253 — Grant performance summary PDF.

Renders a 1-2 page PDF for a single grant showing:
  - Grant title, donor, status, deadline
  - Application count by status
  - AI vs human delta summary
  - Top-5 applications by AI score
"""

from __future__ import annotations
import io
import logging

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, Table, TableStyle,
)

logger = logging.getLogger('kuja')

KUJA_CLAY = colors.HexColor('#a55636')
KUJA_INK = colors.HexColor('#1f2937')
KUJA_MUTED = colors.HexColor('#6b7280')


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(KUJA_MUTED)
    canvas.setFont('Helvetica', 8)
    text = f'Page {canvas.getPageNumber()} · Generated by Kuja'
    canvas.drawRightString(A4[0] - 15 * mm, 12 * mm, text)
    canvas.restoreState()


def build_grant_summary_pdf(*, grant, applications, ai_vs_human_delta=None,
                            ai_vs_human_pool=0) -> bytes:
    buf = io.BytesIO()
    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height)
    doc.addPageTemplates([PageTemplate(id='all', frames=[frame], onPage=_footer)])

    title_style = ParagraphStyle(
        'title', fontName='Helvetica-Bold', fontSize=18, textColor=KUJA_CLAY,
        spaceAfter=8,
    )
    h_style = ParagraphStyle(
        'h', fontName='Helvetica-Bold', fontSize=11, textColor=KUJA_INK,
        spaceBefore=10, spaceAfter=4,
    )
    p_style = ParagraphStyle(
        'p', fontName='Helvetica', fontSize=10, textColor=KUJA_INK, leading=14,
    )
    muted_style = ParagraphStyle(
        'muted', fontName='Helvetica', fontSize=9, textColor=KUJA_MUTED,
    )

    story = []
    story.append(Paragraph(f'Grant performance summary', title_style))
    story.append(Paragraph(grant.title, h_style))
    if grant.donor_org:
        story.append(Paragraph(f'Donor: {grant.donor_org.name}', muted_style))
    if grant.deadline:
        story.append(Paragraph(f'Deadline: {grant.deadline.strftime("%Y-%m-%d")}', muted_style))
    story.append(Paragraph(f'Status: {grant.status}', muted_style))
    story.append(Spacer(1, 8))

    by_status = {}
    for a in applications:
        by_status[a.status] = by_status.get(a.status, 0) + 1
    story.append(Paragraph('Applications by status', h_style))
    if by_status:
        rows = [['Status', 'Count']]
        for k, v in sorted(by_status.items(), key=lambda x: -x[1]):
            rows.append([k, str(v)])
        tbl = Table(rows, colWidths=[80 * mm, 40 * mm])
        tbl.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BACKGROUND', (0, 0), (-1, 0), KUJA_CLAY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.25, KUJA_MUTED),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(tbl)
    else:
        story.append(Paragraph('No applications received yet.', muted_style))

    if ai_vs_human_delta is not None and ai_vs_human_pool >= 1:
        story.append(Paragraph('AI vs human calibration', h_style))
        sign = '+' if ai_vs_human_delta >= 0 else ''
        story.append(Paragraph(
            f'Mean (human − AI) score delta across {ai_vs_human_pool} scored '
            f'application(s): <b>{sign}{ai_vs_human_delta}</b>',
            p_style,
        ))

    scored = sorted(
        [a for a in applications if a.ai_score is not None],
        key=lambda a: -a.ai_score,
    )[:5]
    if scored:
        story.append(Paragraph('Top 5 applications by AI score', h_style))
        rows = [['Org', 'AI', 'Human', 'Status']]
        for a in scored:
            rows.append([
                (a.ngo_org.name if a.ngo_org else '—')[:60],
                str(round(a.ai_score)) if a.ai_score is not None else '—',
                str(round(a.human_score)) if a.human_score is not None else '—',
                a.status,
            ])
        tbl = Table(rows, colWidths=[100 * mm, 20 * mm, 20 * mm, 30 * mm])
        tbl.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BACKGROUND', (0, 0), (-1, 0), KUJA_CLAY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('GRID', (0, 0), (-1, -1), 0.25, KUJA_MUTED),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(tbl)

    doc.build(story)
    pdf = buf.getvalue()
    buf.close()
    return pdf
