"""Phase 1.1 — i18n keys for the application co-author UI."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

KEYS = {
    "en": {
        "common.close": "Close",
        "coauthor.cta.open": "Generate first draft",
        "coauthor.cta.generate": "Generate draft",
        "coauthor.cta.generating": "Generating…",
        "coauthor.cta.regenerate": "Regenerate",
        "coauthor.heading": "AI co-author",
        "coauthor.subtitle": "Type a short brief in any language. We'll use your org profile, prior applications, and uploaded documents to generate a complete first draft of every section. Edit anything before submitting.",
        "coauthor.brief_label": "Brief (optional)",
        "coauthor.brief_placeholder": "e.g. We want to focus on female-led smallholder farms in Kakamega using SMS-based agronomy coaching, drawing on our 2024 maize program.",
        "coauthor.replace_existing": "Replace my existing answers",
        "coauthor.voice_note_label": "Tonal note",
        "coauthor.draft_summary": "{n} drafted answers · {citations} citations",
        "coauthor.provenance_label": "Sources cited",
        "coauthor.applied_to_form": "Applied to your form — review and edit",
        "coauthor.preview_only": "Preview only — start an application to apply",
        "coauthor.confidence.high": "High",
        "coauthor.confidence.medium": "Medium",
        "coauthor.confidence.low": "Low",
        "coauthor.toast.draft_ready": "Draft ready: {n} answers, {provenance} citations",
    },
    "ar": {
        "common.close": "إغلاق",
        "coauthor.cta.open": "أنشئ مسودة أولى",
        "coauthor.cta.generate": "أنشئ المسودة",
        "coauthor.cta.generating": "جارٍ الإنشاء…",
        "coauthor.cta.regenerate": "إعادة الإنشاء",
        "coauthor.heading": "مساعد الكتابة بالذكاء الاصطناعي",
        "coauthor.subtitle": "اكتب موجزاً قصيراً بأي لغة. سنستخدم ملف منظمتك والطلبات السابقة والمستندات المرفوعة لإنشاء مسودة أولى متكاملة لكل قسم. يمكنك تعديل كل شيء قبل التقديم.",
        "coauthor.brief_label": "موجز (اختياري)",
        "coauthor.brief_placeholder": "مثال: نريد التركيز على المزارعات الصغيرات في كاكاميغا عبر تدريب زراعي بالرسائل النصية، مستندين إلى برنامج الذرة لدينا لعام 2024.",
        "coauthor.replace_existing": "استبدال إجاباتي الحالية",
        "coauthor.voice_note_label": "ملاحظة على النبرة",
        "coauthor.draft_summary": "{n} إجابة مسوّدة · {citations} مرجع",
        "coauthor.provenance_label": "المصادر المستشهد بها",
        "coauthor.applied_to_form": "تم التطبيق على نموذجك — راجع وعدّل",
        "coauthor.preview_only": "معاينة فقط — ابدأ طلباً لتطبيق المسودة",
        "coauthor.confidence.high": "مرتفعة",
        "coauthor.confidence.medium": "متوسطة",
        "coauthor.confidence.low": "منخفضة",
        "coauthor.toast.draft_ready": "المسودة جاهزة: {n} إجابة، {provenance} مرجع",
    },
    "fr": {
        "common.close": "Fermer",
        "coauthor.cta.open": "Générer un premier brouillon",
        "coauthor.cta.generate": "Générer le brouillon",
        "coauthor.cta.generating": "Génération…",
        "coauthor.cta.regenerate": "Régénérer",
        "coauthor.heading": "Co-auteur IA",
        "coauthor.subtitle": "Saisissez un court résumé dans n'importe quelle langue. Nous utiliserons votre profil d'organisation, vos candidatures antérieures et vos documents pour produire un premier brouillon complet. Modifiez librement avant soumission.",
        "coauthor.brief_label": "Résumé (facultatif)",
        "coauthor.brief_placeholder": "Ex. : nous ciblons les petites exploitations dirigées par des femmes à Kakamega via un coaching agronomique par SMS, en nous appuyant sur notre programme maïs 2024.",
        "coauthor.replace_existing": "Remplacer mes réponses actuelles",
        "coauthor.voice_note_label": "Note tonale",
        "coauthor.draft_summary": "{n} réponses · {citations} citations",
        "coauthor.provenance_label": "Sources citées",
        "coauthor.applied_to_form": "Appliqué à votre formulaire — relisez et éditez",
        "coauthor.preview_only": "Aperçu uniquement — démarrez une candidature pour appliquer",
        "coauthor.confidence.high": "Élevée",
        "coauthor.confidence.medium": "Moyenne",
        "coauthor.confidence.low": "Faible",
        "coauthor.toast.draft_ready": "Brouillon prêt : {n} réponses, {provenance} citations",
    },
    "es": {
        "common.close": "Cerrar",
        "coauthor.cta.open": "Generar primer borrador",
        "coauthor.cta.generate": "Generar borrador",
        "coauthor.cta.generating": "Generando…",
        "coauthor.cta.regenerate": "Regenerar",
        "coauthor.heading": "Coautor IA",
        "coauthor.subtitle": "Escribe un breve resumen en cualquier idioma. Usaremos el perfil de tu organización, postulaciones previas y documentos cargados para generar un primer borrador completo. Edita lo que quieras antes de enviar.",
        "coauthor.brief_label": "Resumen (opcional)",
        "coauthor.brief_placeholder": "Ej.: queremos enfocarnos en pequeñas agricultoras en Kakamega usando coaching agrícola por SMS, basándonos en nuestro programa de maíz 2024.",
        "coauthor.replace_existing": "Reemplazar mis respuestas actuales",
        "coauthor.voice_note_label": "Nota de tono",
        "coauthor.draft_summary": "{n} respuestas · {citations} citas",
        "coauthor.provenance_label": "Fuentes citadas",
        "coauthor.applied_to_form": "Aplicado a tu formulario — revisa y edita",
        "coauthor.preview_only": "Solo vista previa — inicia una postulación para aplicar",
        "coauthor.confidence.high": "Alta",
        "coauthor.confidence.medium": "Media",
        "coauthor.confidence.low": "Baja",
        "coauthor.toast.draft_ready": "Borrador listo: {n} respuestas, {provenance} citas",
    },
    "sw": {
        "common.close": "Funga",
        "coauthor.cta.open": "Tengeneza rasimu ya kwanza",
        "coauthor.cta.generate": "Tengeneza rasimu",
        "coauthor.cta.generating": "Inatengeneza…",
        "coauthor.cta.regenerate": "Tengeneza tena",
        "coauthor.heading": "Mwandishi mwenza wa AI",
        "coauthor.subtitle": "Andika muhtasari mfupi kwa lugha yoyote. Tutatumia wasifu wa shirika lako, maombi ya awali, na hati zilizopakiwa kutengeneza rasimu kamili ya kwanza. Hariri chochote kabla ya kuwasilisha.",
        "coauthor.brief_label": "Muhtasari (hiari)",
        "coauthor.brief_placeholder": "Mfano: tunalenga wakulima wadogo wa kike huko Kakamega kupitia mafunzo ya kilimo ya SMS, kwa kutegemea programu yetu ya mahindi ya 2024.",
        "coauthor.replace_existing": "Badilisha majibu yangu yaliyopo",
        "coauthor.voice_note_label": "Maelezo ya sauti",
        "coauthor.draft_summary": "majibu {n} · marejeleo {citations}",
        "coauthor.provenance_label": "Vyanzo vilivyotajwa",
        "coauthor.applied_to_form": "Imewekwa kwenye fomu — kagua na hariri",
        "coauthor.preview_only": "Onyesho la awali tu — anzisha ombi ili kuweka",
        "coauthor.confidence.high": "Juu",
        "coauthor.confidence.medium": "Wastani",
        "coauthor.confidence.low": "Chini",
        "coauthor.toast.draft_ready": "Rasimu tayari: majibu {n}, marejeleo {provenance}",
    },
    "so": {
        "common.close": "Xidh",
        "coauthor.cta.open": "Soo saar qabyo koowaad",
        "coauthor.cta.generate": "Soo saar qabyada",
        "coauthor.cta.generating": "Waxaa la sameynayaa…",
        "coauthor.cta.regenerate": "Mar kale soo saar",
        "coauthor.heading": "Wada-qoraha AI",
        "coauthor.subtitle": "Ku qor warbixin gaaban luuqad kasta. Waxaan isticmaali doonnaa sumadda ururkaaga, codsiyada hore, iyo dukumeentiyada la soo dhejiyay si aan u soo saarno qabyo koowaad oo dhammeystiran. Wax kasta wax ka beddel ka hor inta aadan gudbin.",
        "coauthor.brief_label": "Warbixin (ikhtiyaari)",
        "coauthor.brief_placeholder": "Tusaale: waxaan diiradda saareynaa beeralayda yaryar ee haweenku hoggaaminayaan ee Kakamega iyadoo la adeegsanayo tababar SMS ah, oo lagu salaynayo barnaamijkayaga galleyda 2024.",
        "coauthor.replace_existing": "Beddel jawaabahayga jira",
        "coauthor.voice_note_label": "Qoraal ku saabsan codka",
        "coauthor.draft_summary": "{n} jawaab oo qabyo ah · {citations} tixraac",
        "coauthor.provenance_label": "Ilaha la xusay",
        "coauthor.applied_to_form": "Waxaa loo dabaqay foomkaaga — eeg oo wax ka beddel",
        "coauthor.preview_only": "Horudhac kaliya — bilow codsi si aad u dabajiso",
        "coauthor.confidence.high": "Sare",
        "coauthor.confidence.medium": "Dhexdhexaad",
        "coauthor.confidence.low": "Hoose",
        "coauthor.toast.draft_ready": "Qabyada diyaar: {n} jawaab, {provenance} tixraac",
    },
}

for lang, additions in KEYS.items():
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lang}: +{added}")
