"""Phase 0.3 — add server.error.* keys to the canonical i18n catalog.

These render the human-facing message inside API error responses. The
machine error code (left of 'message') stays English because tests,
monitoring, and frontend conditionals key off it.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

KEYS = {
    "en": {
        "server.error.auth.required": "Authentication required.",
        "server.error.auth.admin_only": "Admin access required.",
        "server.error.auth.access_denied": "You don't have permission to do this.",
        "server.error.auth.too_many_attempts": "Too many login attempts. Please wait a few minutes before trying again.",
        "server.error.auth.account_locked": "Account locked. Try again in a few minutes.",
        "server.error.auth.invalid_credentials": "Invalid email or password.",
        "server.error.grant.not_found": "Grant not found.",
        "server.error.grant.deadline_passed": "The application deadline has passed.",
        "server.error.grant.not_open": "This grant is not currently accepting applications.",
        "server.error.grant.already_applied": "Your organization has already applied to this grant.",
        "server.error.application.not_found": "Application not found.",
        "server.error.application.cannot_modify": "This application can no longer be modified.",
        "server.error.review.not_found": "Review not found.",
        "server.error.review.not_assigned": "You are not assigned to this review.",
        "server.error.report.not_found": "Report not found.",
        "server.error.report.already_submitted": "Report already submitted.",
        "server.error.upload.no_file": "No file provided.",
        "server.error.upload.empty_file": "File is empty or too small to contain valid content.",
        "server.error.upload.too_large": "File too large. Maximum size is {max_mb} MB.",
        "server.error.upload.unsupported_type": "Unsupported file type ({ext}). Allowed: {allowed}.",
        "server.error.upload.pdf_no_pages": "PDF has no pages. Please upload a valid PDF document.",
        "server.error.upload.pdf_unreadable": "Could not read the PDF file. It may be corrupted or password-protected.",
        "server.error.upload.docx_unreadable": "Could not read the Word document. It may be corrupted.",
        "server.error.upload.no_text": "No readable text found. The document may be empty, scanned, or corrupted.",
        "server.error.ai.unavailable": "AI is temporarily unavailable. Please try again in a moment.",
        "server.error.ai.rate_limited": "Too many AI requests. Please wait a moment.",
        "server.error.ai.invalid_input": "AI request is missing required input.",
        "server.error.validation.missing_field": "{field} is required.",
        "server.error.validation.invalid_value": "{field} value is invalid.",
        "server.error.server.unexpected": "Something went wrong. We've logged this and will investigate.",
    },
    "ar": {
        "server.error.auth.required": "يلزم تسجيل الدخول.",
        "server.error.auth.admin_only": "هذا الإجراء مخصص للمسؤولين فقط.",
        "server.error.auth.access_denied": "ليس لديك صلاحية القيام بذلك.",
        "server.error.auth.too_many_attempts": "محاولات تسجيل دخول كثيرة. الرجاء الانتظار بضع دقائق ثم إعادة المحاولة.",
        "server.error.auth.account_locked": "الحساب مقفل. الرجاء المحاولة بعد بضع دقائق.",
        "server.error.auth.invalid_credentials": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
        "server.error.grant.not_found": "لم يتم العثور على المنحة.",
        "server.error.grant.deadline_passed": "انتهى الموعد النهائي لتقديم الطلبات.",
        "server.error.grant.not_open": "هذه المنحة لا تقبل طلبات حالياً.",
        "server.error.grant.already_applied": "سبق لمنظمتك التقدّم لهذه المنحة.",
        "server.error.application.not_found": "لم يتم العثور على الطلب.",
        "server.error.application.cannot_modify": "لم يعد بالإمكان تعديل هذا الطلب.",
        "server.error.review.not_found": "لم يتم العثور على المراجعة.",
        "server.error.review.not_assigned": "هذه المراجعة ليست موكَلة إليك.",
        "server.error.report.not_found": "لم يتم العثور على التقرير.",
        "server.error.report.already_submitted": "تم تقديم التقرير مسبقاً.",
        "server.error.upload.no_file": "لم يتم إرفاق أي ملف.",
        "server.error.upload.empty_file": "الملف فارغ أو صغير جداً ولا يحتوي على محتوى صالح.",
        "server.error.upload.too_large": "الملف كبير جداً. الحد الأقصى للحجم هو {max_mb} ميغابايت.",
        "server.error.upload.unsupported_type": "نوع الملف غير مدعوم ({ext}). الأنواع المسموح بها: {allowed}.",
        "server.error.upload.pdf_no_pages": "ملف PDF لا يحتوي على صفحات. الرجاء رفع مستند PDF صالح.",
        "server.error.upload.pdf_unreadable": "تعذّرت قراءة ملف PDF. قد يكون تالفاً أو محمياً بكلمة مرور.",
        "server.error.upload.docx_unreadable": "تعذّرت قراءة مستند Word. قد يكون تالفاً.",
        "server.error.upload.no_text": "لا يوجد نص قابل للقراءة في الملف. قد يكون فارغاً أو ممسوحاً ضوئياً أو تالفاً.",
        "server.error.ai.unavailable": "الذكاء الاصطناعي غير متاح مؤقتاً. الرجاء المحاولة بعد لحظات.",
        "server.error.ai.rate_limited": "طلبات ذكاء اصطناعي كثيرة جداً. الرجاء الانتظار قليلاً.",
        "server.error.ai.invalid_input": "ينقص الطلب مدخلات مطلوبة لتشغيل الذكاء الاصطناعي.",
        "server.error.validation.missing_field": "{field} مطلوب.",
        "server.error.validation.invalid_value": "قيمة {field} غير صالحة.",
        "server.error.server.unexpected": "حدث خطأ غير متوقع. تم تسجيله وسنحقّق فيه.",
    },
    "fr": {
        "server.error.auth.required": "Authentification requise.",
        "server.error.auth.admin_only": "Accès administrateur requis.",
        "server.error.auth.access_denied": "Vous n'avez pas la permission d'effectuer cette action.",
        "server.error.auth.too_many_attempts": "Trop de tentatives de connexion. Patientez quelques minutes avant de réessayer.",
        "server.error.auth.account_locked": "Compte verrouillé. Réessayez dans quelques minutes.",
        "server.error.auth.invalid_credentials": "E-mail ou mot de passe invalide.",
        "server.error.grant.not_found": "Subvention introuvable.",
        "server.error.grant.deadline_passed": "La date limite de candidature est dépassée.",
        "server.error.grant.not_open": "Cette subvention n'accepte pas de candidatures pour le moment.",
        "server.error.grant.already_applied": "Votre organisation a déjà postulé à cette subvention.",
        "server.error.application.not_found": "Candidature introuvable.",
        "server.error.application.cannot_modify": "Cette candidature ne peut plus être modifiée.",
        "server.error.review.not_found": "Évaluation introuvable.",
        "server.error.review.not_assigned": "Cette évaluation ne vous est pas attribuée.",
        "server.error.report.not_found": "Rapport introuvable.",
        "server.error.report.already_submitted": "Le rapport a déjà été soumis.",
        "server.error.upload.no_file": "Aucun fichier fourni.",
        "server.error.upload.empty_file": "Le fichier est vide ou trop petit pour contenir un contenu valide.",
        "server.error.upload.too_large": "Fichier trop volumineux. Taille maximale : {max_mb} Mo.",
        "server.error.upload.unsupported_type": "Type de fichier non pris en charge ({ext}). Autorisés : {allowed}.",
        "server.error.upload.pdf_no_pages": "Le PDF ne contient aucune page. Téléversez un document PDF valide.",
        "server.error.upload.pdf_unreadable": "Impossible de lire le PDF. Il est peut-être corrompu ou protégé.",
        "server.error.upload.docx_unreadable": "Impossible de lire le document Word. Il est peut-être corrompu.",
        "server.error.upload.no_text": "Aucun texte lisible trouvé. Le document est peut-être vide, scanné ou corrompu.",
        "server.error.ai.unavailable": "L'IA est temporairement indisponible. Réessayez dans un instant.",
        "server.error.ai.rate_limited": "Trop de requêtes IA. Patientez un instant.",
        "server.error.ai.invalid_input": "La requête IA manque d'informations requises.",
        "server.error.validation.missing_field": "{field} est requis.",
        "server.error.validation.invalid_value": "La valeur de {field} est invalide.",
        "server.error.server.unexpected": "Une erreur inattendue s'est produite. Nous l'avons enregistrée.",
    },
    "es": {
        "server.error.auth.required": "Se requiere autenticación.",
        "server.error.auth.admin_only": "Se requiere acceso de administrador.",
        "server.error.auth.access_denied": "No tienes permiso para hacer esto.",
        "server.error.auth.too_many_attempts": "Demasiados intentos de inicio de sesión. Espera unos minutos.",
        "server.error.auth.account_locked": "Cuenta bloqueada. Inténtalo en unos minutos.",
        "server.error.auth.invalid_credentials": "Correo o contraseña inválidos.",
        "server.error.grant.not_found": "Subvención no encontrada.",
        "server.error.grant.deadline_passed": "La fecha límite de la postulación ha pasado.",
        "server.error.grant.not_open": "Esta subvención no acepta postulaciones por ahora.",
        "server.error.grant.already_applied": "Tu organización ya postuló a esta subvención.",
        "server.error.application.not_found": "Postulación no encontrada.",
        "server.error.application.cannot_modify": "Esta postulación ya no se puede modificar.",
        "server.error.review.not_found": "Revisión no encontrada.",
        "server.error.review.not_assigned": "No tienes esta revisión asignada.",
        "server.error.report.not_found": "Informe no encontrado.",
        "server.error.report.already_submitted": "El informe ya fue enviado.",
        "server.error.upload.no_file": "No se proporcionó ningún archivo.",
        "server.error.upload.empty_file": "El archivo está vacío o es demasiado pequeño.",
        "server.error.upload.too_large": "Archivo demasiado grande. Tamaño máximo: {max_mb} MB.",
        "server.error.upload.unsupported_type": "Tipo de archivo no admitido ({ext}). Permitidos: {allowed}.",
        "server.error.upload.pdf_no_pages": "El PDF no tiene páginas. Sube un PDF válido.",
        "server.error.upload.pdf_unreadable": "No se pudo leer el PDF. Puede estar dañado o protegido.",
        "server.error.upload.docx_unreadable": "No se pudo leer el documento Word. Puede estar dañado.",
        "server.error.upload.no_text": "No se encontró texto legible. El documento puede estar vacío o escaneado.",
        "server.error.ai.unavailable": "La IA no está disponible temporalmente. Inténtalo en un momento.",
        "server.error.ai.rate_limited": "Demasiadas solicitudes de IA. Espera un momento.",
        "server.error.ai.invalid_input": "Falta información requerida para la solicitud de IA.",
        "server.error.validation.missing_field": "{field} es requerido.",
        "server.error.validation.invalid_value": "El valor de {field} es inválido.",
        "server.error.server.unexpected": "Algo salió mal. Lo registramos y lo investigaremos.",
    },
    "sw": {
        "server.error.auth.required": "Uthibitisho unahitajika.",
        "server.error.auth.admin_only": "Ufikiaji wa msimamizi unahitajika.",
        "server.error.auth.access_denied": "Huna ruhusa ya kufanya hili.",
        "server.error.auth.too_many_attempts": "Majaribio mengi ya kuingia. Tafadhali subiri dakika chache na ujaribu tena.",
        "server.error.auth.account_locked": "Akaunti imefungwa. Jaribu tena baada ya dakika chache.",
        "server.error.auth.invalid_credentials": "Barua pepe au nenosiri si sahihi.",
        "server.error.grant.not_found": "Ruzuku haijapatikana.",
        "server.error.grant.deadline_passed": "Tarehe ya mwisho ya kuomba imepita.",
        "server.error.grant.not_open": "Ruzuku hii haikubali maombi kwa sasa.",
        "server.error.grant.already_applied": "Shirika lako tayari limeomba ruzuku hii.",
        "server.error.application.not_found": "Ombi halijapatikana.",
        "server.error.application.cannot_modify": "Ombi hili haliwezi kubadilishwa tena.",
        "server.error.review.not_found": "Ukaguzi haujapatikana.",
        "server.error.review.not_assigned": "Hujapewa ukaguzi huu.",
        "server.error.report.not_found": "Ripoti haijapatikana.",
        "server.error.report.already_submitted": "Ripoti tayari imewasilishwa.",
        "server.error.upload.no_file": "Hakuna faili lililotumwa.",
        "server.error.upload.empty_file": "Faili limejaa au ni dogo sana.",
        "server.error.upload.too_large": "Faili kubwa sana. Ukubwa wa juu: MB {max_mb}.",
        "server.error.upload.unsupported_type": "Aina ya faili haisaidiwi ({ext}). Zinazoruhusiwa: {allowed}.",
        "server.error.upload.pdf_no_pages": "PDF haina kurasa. Pakia PDF halali.",
        "server.error.upload.pdf_unreadable": "Imeshindikana kusoma PDF. Inaweza kuwa imeharibika au inalindwa kwa nenosiri.",
        "server.error.upload.docx_unreadable": "Imeshindikana kusoma hati ya Word. Inaweza kuwa imeharibika.",
        "server.error.upload.no_text": "Hakuna maandishi yanayoweza kusomeka. Hati inaweza kuwa tupu au iliyoskaniwa.",
        "server.error.ai.unavailable": "AI haipo kwa muda. Tafadhali jaribu baadae.",
        "server.error.ai.rate_limited": "Maombi mengi ya AI. Subiri kidogo.",
        "server.error.ai.invalid_input": "Ombi la AI linakosa maelezo yanayohitajika.",
        "server.error.validation.missing_field": "{field} inahitajika.",
        "server.error.validation.invalid_value": "Thamani ya {field} si halali.",
        "server.error.server.unexpected": "Kuna tatizo. Tumeliandika na tutachunguza.",
    },
    "so": {
        "server.error.auth.required": "Lagu baahan yahay xaqiijinta.",
        "server.error.auth.admin_only": "Waxaa loo baahan yahay xulnoolaha maamulka.",
        "server.error.auth.access_denied": "Ma haysatid ogolaansho aad tan u sameyso.",
        "server.error.auth.too_many_attempts": "Isku-day badan oo gelitaan. Fadlan sug daqiiqado yar oo isku day mar kale.",
        "server.error.auth.account_locked": "Akoonkii waa la xidhay. Isku day daqiiqado yar ka dib.",
        "server.error.auth.invalid_credentials": "Iimaylka ama erayga sirta ah waa khalad.",
        "server.error.grant.not_found": "Deeqda lama helin.",
        "server.error.grant.deadline_passed": "Wakhtigii ugu dambeeyay ee codsiga waa dhaafay.",
        "server.error.grant.not_open": "Deeqdani hadda ma aqbaleyso codsiyo.",
        "server.error.grant.already_applied": "Ururkaagu hore ayuu deeqdan u codsaday.",
        "server.error.application.not_found": "Codsiga lama helin.",
        "server.error.application.cannot_modify": "Codsigan dib looma beddeli karo.",
        "server.error.review.not_found": "Eegista lama helin.",
        "server.error.review.not_assigned": "Eegistan adigaa la kuu xilsaarin.",
        "server.error.report.not_found": "Warbixinta lama helin.",
        "server.error.report.already_submitted": "Warbixinta hore ayaa la gudbiyay.",
        "server.error.upload.no_file": "Ma jiro fayl la soo dhejiyay.",
        "server.error.upload.empty_file": "Faylku waa madhan yahay ama aad ayuu u yaryahay.",
        "server.error.upload.too_large": "Faylka aad ayuu u weyn yahay. Cabbirka ugu badan: {max_mb} MB.",
        "server.error.upload.unsupported_type": "Nooca faylka lama taageero ({ext}). Kuwa la oggol yahay: {allowed}.",
        "server.error.upload.pdf_no_pages": "PDF-ku ma laha bogag. Soo dhejii PDF sax ah.",
        "server.error.upload.pdf_unreadable": "Lama akhriyi karo faylka PDF. Wuxuu noqon karaa mid khasaaray ama lacag-sirta leh.",
        "server.error.upload.docx_unreadable": "Lama akhriyi karo dukumeentiga Word. Wuxuu noqon karaa mid khasaaray.",
        "server.error.upload.no_text": "Lama helin qoraal la akhriyi karo. Dukumeentigu waa madhan yahay ama waa la sawiray.",
        "server.error.ai.unavailable": "AI hadda lama heli karo. Fadlan isku day daqiiqado yar ka dib.",
        "server.error.ai.rate_limited": "Codsiyo AI ah oo aad u badan. Sug daqiiqad yar.",
        "server.error.ai.invalid_input": "Codsiga AI-da waxaa ka maqan macluumaad la rabo.",
        "server.error.validation.missing_field": "{field} ayaa loo baahan yahay.",
        "server.error.validation.invalid_value": "Qiimaha {field} ma saxna.",
        "server.error.server.unexpected": "Wax baa qaldamay. Waan diiwaan-galinnay.",
    },
}

for lang, additions in KEYS.items():
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lang}: +{added} server.error.* keys")
