"""Add review/applications/reports localization keys (35+ strings)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

KEYS = {
    "en": {
        # Reviewer queue page
        "review.title_assignments": "Review assignments",
        "review.subtitle_queue": "AI-prioritized queue with comparison support",
        "review.tab.pending_count": "Pending ({n})",
        "review.tab.completed_count": "Completed ({n})",
        "review.no_pending_title": "No pending assignments",
        "review.no_pending_body": "You have no applications to review right now.",
        "review.no_completed_title": "No completed reviews",
        "review.no_completed_body": "Reviews you complete will appear here.",
        "review.start_review_btn": "Start review",
        # Donor reviews view
        "review.donor_title": "Applications to review",
        "review.filter_all_grants": "All grants ({n})",
        "review.no_apps_donor_title": "No applications",
        "review.no_apps_donor_body": "Applications will appear here as NGOs submit them.",
        # Common columns (reused across tables)
        "common.col.applicant": "Applicant",
        "common.col.grant": "Grant",
        "common.col.status": "Status",
        "common.col.actions": "Actions",
        "common.col.score": "Score",
        "common.col.completed": "Completed",
        "common.col.application": "Application",
        "common.col.view": "View",
        "common.back": "Back",
        # Review detail
        "review.detail.tab.responses": "Responses",
        "review.detail.tab.documents": "Documents",
        "review.detail.tab.scores": "Scores",
        "review.detail.weighted_total": "Weighted total: {n}%",
        "review.detail.based_on_criteria": "Based on {n} criteria",
        "review.detail.submit_btn": "Submit scores",
        "review.detail.feedback_placeholder": "Provide feedback on this criterion…",
        # Completed reviews
        "review.completed_title": "Completed reviews",
        "review.completed.empty_title": "No completed reviews yet",
        "review.completed.empty_body": "Reviews you complete will be listed here for reference.",
        "review.completed.view_pending_btn": "View pending assignments",
        # Applications detail tabs
        "applications.documents_empty": "Documents uploaded with this application will appear here",
        "applications.reviews_empty": "Reviewer scores and comments will appear here",
        "applications.eligibility_responses": "Eligibility responses",
        "applications.scores_empty": "Scores will appear after AI and reviewer evaluation",
        "applications.score_overview": "Score overview",
        "applications.score.ai": "AI Score",
        "applications.score.human": "Human",
        "applications.score.final": "Final",
        "applications.word_count": "{n} words",
        # Compliance
        "compliance.due_label": "Due: {date}",
        "compliance.status_at_risk": "at risk",
        "compliance.no_reports_yet": "No reports for this grant yet.",
    },
    "ar": {
        "review.title_assignments": "مهام المراجعة",
        "review.subtitle_queue": "قائمة مرتّبة بالذكاء الاصطناعي مع دعم المقارنة",
        "review.tab.pending_count": "قيد الانتظار ({n})",
        "review.tab.completed_count": "مكتملة ({n})",
        "review.no_pending_title": "لا توجد مهام معلّقة",
        "review.no_pending_body": "ليس لديك طلبات لمراجعتها حاليًا.",
        "review.no_completed_title": "لا توجد مراجعات مكتملة",
        "review.no_completed_body": "ستظهر هنا المراجعات التي تكملها.",
        "review.start_review_btn": "ابدأ المراجعة",
        "review.donor_title": "الطلبات للمراجعة",
        "review.filter_all_grants": "جميع المنح ({n})",
        "review.no_apps_donor_title": "لا توجد طلبات",
        "review.no_apps_donor_body": "ستظهر الطلبات هنا حين تقدّمها المنظمات.",
        "common.col.applicant": "المتقدّم",
        "common.col.grant": "المنحة",
        "common.col.status": "الحالة",
        "common.col.actions": "إجراءات",
        "common.col.score": "الدرجة",
        "common.col.completed": "تاريخ الإكمال",
        "common.col.application": "الطلب",
        "common.col.view": "عرض",
        "common.back": "رجوع",
        "review.detail.tab.responses": "الردود",
        "review.detail.tab.documents": "المستندات",
        "review.detail.tab.scores": "الدرجات",
        "review.detail.weighted_total": "الإجمالي المرجَّح: {n}%",
        "review.detail.based_on_criteria": "بناءً على {n} معيارًا",
        "review.detail.submit_btn": "إرسال الدرجات",
        "review.detail.feedback_placeholder": "قدّم ملاحظات على هذا المعيار…",
        "review.completed_title": "المراجعات المكتملة",
        "review.completed.empty_title": "لا توجد مراجعات مكتملة بعد",
        "review.completed.empty_body": "ستُدرج هنا المراجعات التي تكملها للرجوع إليها.",
        "review.completed.view_pending_btn": "عرض المهام المعلّقة",
        "applications.documents_empty": "ستظهر هنا المستندات المرفقة بهذا الطلب",
        "applications.reviews_empty": "ستظهر هنا درجات المراجعين وتعليقاتهم",
        "applications.eligibility_responses": "ردود الأهلية",
        "applications.scores_empty": "ستظهر الدرجات بعد تقييم الذكاء الاصطناعي والمراجعين",
        "applications.score_overview": "نظرة عامة على الدرجات",
        "applications.score.ai": "درجة الذكاء الاصطناعي",
        "applications.score.human": "بشرية",
        "applications.score.final": "نهائية",
        "applications.word_count": "{n} كلمة",
        "compliance.due_label": "الاستحقاق: {date}",
        "compliance.status_at_risk": "في خطر",
        "compliance.no_reports_yet": "لا توجد تقارير لهذه المنحة بعد.",
    },
    "fr": {
        "review.title_assignments": "Affectations de revue",
        "review.subtitle_queue": "File priorisée par IA avec comparaison",
        "review.tab.pending_count": "En attente ({n})",
        "review.tab.completed_count": "Terminées ({n})",
        "review.no_pending_title": "Aucune affectation en attente",
        "review.no_pending_body": "Vous n'avez aucune candidature à examiner pour l'instant.",
        "review.no_completed_title": "Aucune revue terminée",
        "review.no_completed_body": "Vos revues terminées apparaîtront ici.",
        "review.start_review_btn": "Démarrer la revue",
        "review.donor_title": "Candidatures à examiner",
        "review.filter_all_grants": "Toutes les subventions ({n})",
        "review.no_apps_donor_title": "Aucune candidature",
        "review.no_apps_donor_body": "Les candidatures apparaîtront ici à mesure que les ONG les soumettent.",
        "common.col.applicant": "Candidat",
        "common.col.grant": "Subvention",
        "common.col.status": "Statut",
        "common.col.actions": "Actions",
        "common.col.score": "Score",
        "common.col.completed": "Terminée",
        "common.col.application": "Candidature",
        "common.col.view": "Voir",
        "common.back": "Retour",
        "review.detail.tab.responses": "Réponses",
        "review.detail.tab.documents": "Documents",
        "review.detail.tab.scores": "Scores",
        "review.detail.weighted_total": "Total pondéré : {n}%",
        "review.detail.based_on_criteria": "Sur {n} critères",
        "review.detail.submit_btn": "Soumettre les scores",
        "review.detail.feedback_placeholder": "Donnez votre avis sur ce critère…",
        "review.completed_title": "Revues terminées",
        "review.completed.empty_title": "Aucune revue terminée pour le moment",
        "review.completed.empty_body": "Vos revues terminées seront listées ici pour référence.",
        "review.completed.view_pending_btn": "Voir les affectations en attente",
        "applications.documents_empty": "Les documents joints à cette candidature apparaîtront ici",
        "applications.reviews_empty": "Les scores et commentaires des évaluateurs apparaîtront ici",
        "applications.eligibility_responses": "Réponses d'éligibilité",
        "applications.scores_empty": "Les scores apparaîtront après l'évaluation IA et humaine",
        "applications.score_overview": "Aperçu des scores",
        "applications.score.ai": "Score IA",
        "applications.score.human": "Humain",
        "applications.score.final": "Final",
        "applications.word_count": "{n} mots",
        "compliance.due_label": "Échéance : {date}",
        "compliance.status_at_risk": "à risque",
        "compliance.no_reports_yet": "Aucun rapport pour cette subvention.",
    },
    "es": {
        "review.title_assignments": "Asignaciones de revisión",
        "review.subtitle_queue": "Cola priorizada por IA con soporte de comparación",
        "review.tab.pending_count": "Pendientes ({n})",
        "review.tab.completed_count": "Completadas ({n})",
        "review.no_pending_title": "Sin asignaciones pendientes",
        "review.no_pending_body": "No tienes postulaciones por revisar en este momento.",
        "review.no_completed_title": "Sin revisiones completadas",
        "review.no_completed_body": "Las revisiones que completes aparecerán aquí.",
        "review.start_review_btn": "Iniciar revisión",
        "review.donor_title": "Postulaciones a revisar",
        "review.filter_all_grants": "Todas las subvenciones ({n})",
        "review.no_apps_donor_title": "Sin postulaciones",
        "review.no_apps_donor_body": "Las postulaciones aparecerán aquí cuando las ONG las envíen.",
        "common.col.applicant": "Postulante",
        "common.col.grant": "Subvención",
        "common.col.status": "Estado",
        "common.col.actions": "Acciones",
        "common.col.score": "Puntaje",
        "common.col.completed": "Completada",
        "common.col.application": "Postulación",
        "common.col.view": "Ver",
        "common.back": "Atrás",
        "review.detail.tab.responses": "Respuestas",
        "review.detail.tab.documents": "Documentos",
        "review.detail.tab.scores": "Puntajes",
        "review.detail.weighted_total": "Total ponderado: {n}%",
        "review.detail.based_on_criteria": "Basado en {n} criterios",
        "review.detail.submit_btn": "Enviar puntajes",
        "review.detail.feedback_placeholder": "Ofrece comentarios sobre este criterio…",
        "review.completed_title": "Revisiones completadas",
        "review.completed.empty_title": "Aún no hay revisiones completadas",
        "review.completed.empty_body": "Las revisiones que completes se listarán aquí como referencia.",
        "review.completed.view_pending_btn": "Ver asignaciones pendientes",
        "applications.documents_empty": "Los documentos cargados con esta postulación aparecerán aquí",
        "applications.reviews_empty": "Los puntajes y comentarios de los evaluadores aparecerán aquí",
        "applications.eligibility_responses": "Respuestas de elegibilidad",
        "applications.scores_empty": "Los puntajes aparecerán después de la evaluación IA y humana",
        "applications.score_overview": "Resumen de puntajes",
        "applications.score.ai": "Puntaje IA",
        "applications.score.human": "Humano",
        "applications.score.final": "Final",
        "applications.word_count": "{n} palabras",
        "compliance.due_label": "Vence: {date}",
        "compliance.status_at_risk": "en riesgo",
        "compliance.no_reports_yet": "Aún no hay informes para esta subvención.",
    },
    "sw": {
        "review.title_assignments": "Mgawanyo wa ukaguzi",
        "review.subtitle_queue": "Foleni iliyopangwa na AI yenye usaidizi wa kulinganisha",
        "review.tab.pending_count": "Inasubiri ({n})",
        "review.tab.completed_count": "Imekamilika ({n})",
        "review.no_pending_title": "Hakuna majukumu yanayosubiri",
        "review.no_pending_body": "Huna maombi ya kukagua kwa sasa.",
        "review.no_completed_title": "Hakuna ukaguzi uliokamilika",
        "review.no_completed_body": "Ukaguzi unaomaliza utaonekana hapa.",
        "review.start_review_btn": "Anza ukaguzi",
        "review.donor_title": "Maombi ya kukagua",
        "review.filter_all_grants": "Ruzuku zote ({n})",
        "review.no_apps_donor_title": "Hakuna maombi",
        "review.no_apps_donor_body": "Maombi yataonekana hapa NGO zinavyoyawasilisha.",
        "common.col.applicant": "Mwombaji",
        "common.col.grant": "Ruzuku",
        "common.col.status": "Hali",
        "common.col.actions": "Vitendo",
        "common.col.score": "Alama",
        "common.col.completed": "Iliyokamilika",
        "common.col.application": "Ombi",
        "common.col.view": "Tazama",
        "common.back": "Rudi",
        "review.detail.tab.responses": "Majibu",
        "review.detail.tab.documents": "Hati",
        "review.detail.tab.scores": "Alama",
        "review.detail.weighted_total": "Jumla iliyolingana: {n}%",
        "review.detail.based_on_criteria": "Kulingana na vigezo {n}",
        "review.detail.submit_btn": "Wasilisha alama",
        "review.detail.feedback_placeholder": "Toa maoni kuhusu kigezo hiki…",
        "review.completed_title": "Ukaguzi uliokamilika",
        "review.completed.empty_title": "Bado hakuna ukaguzi uliokamilika",
        "review.completed.empty_body": "Ukaguzi unaomaliza utaorodheshwa hapa kwa marejeleo.",
        "review.completed.view_pending_btn": "Angalia majukumu yanayosubiri",
        "applications.documents_empty": "Hati zilizopakiwa na ombi hili zitaonekana hapa",
        "applications.reviews_empty": "Alama na maoni ya wakaguzi yataonekana hapa",
        "applications.eligibility_responses": "Majibu ya ustahiki",
        "applications.scores_empty": "Alama zitaonekana baada ya tathmini ya AI na mkaguzi",
        "applications.score_overview": "Muhtasari wa alama",
        "applications.score.ai": "Alama ya AI",
        "applications.score.human": "Mtu",
        "applications.score.final": "Mwisho",
        "applications.word_count": "maneno {n}",
        "compliance.due_label": "Inaisha: {date}",
        "compliance.status_at_risk": "hatarini",
        "compliance.no_reports_yet": "Bado hakuna ripoti kwa ruzuku hii.",
    },
    "so": {
        "review.title_assignments": "Hawlaha eegista",
        "review.subtitle_queue": "Safka mudnaanta AI leh oo leh isbarbar dhig",
        "review.tab.pending_count": "Sugaya ({n})",
        "review.tab.completed_count": "La dhammeeyey ({n})",
        "review.no_pending_title": "Ma jiraan hawlo sugaya",
        "review.no_pending_body": "Ma haysatid codsiyo hadda ah oo aad eegtid.",
        "review.no_completed_title": "Ma jiraan eegis dhammaystiran",
        "review.no_completed_body": "Eegisyada aad dhammeyso ayaa halkan ka muuqan doona.",
        "review.start_review_btn": "Bilaaw eegista",
        "review.donor_title": "Codsiyada la eegayo",
        "review.filter_all_grants": "Dhammaan deeqaha ({n})",
        "review.no_apps_donor_title": "Ma jiraan codsiyo",
        "review.no_apps_donor_body": "Codsiyadu waxay halkan ka muuqan doonaan marka NGO-yadu gudbiyaan.",
        "common.col.applicant": "Codsade",
        "common.col.grant": "Deeqda",
        "common.col.status": "Xaalad",
        "common.col.actions": "Falal",
        "common.col.score": "Buundo",
        "common.col.completed": "La dhammeeyey",
        "common.col.application": "Codsi",
        "common.col.view": "Eeg",
        "common.back": "Dib",
        "review.detail.tab.responses": "Jawaabaha",
        "review.detail.tab.documents": "Dukumentiyada",
        "review.detail.tab.scores": "Buundooyinka",
        "review.detail.weighted_total": "Wadarta miisaaman: {n}%",
        "review.detail.based_on_criteria": "Ku saleysan cabbirro {n}",
        "review.detail.submit_btn": "Gudbi buundooyinka",
        "review.detail.feedback_placeholder": "Bixi faallooyin ku saabsan cabbirkan…",
        "review.completed_title": "Eegisyada la dhammeeyey",
        "review.completed.empty_title": "Weli ma jiraan eegisyo dhammaystiran",
        "review.completed.empty_body": "Eegisyada aad dhammeyso waxaa halkan lagu liisan doonaa tixraac.",
        "review.completed.view_pending_btn": "Eeg hawlaha sugaya",
        "applications.documents_empty": "Dukumeentiyada lala soo dhejiyey codsigan ayaa halkan ka muuqan doona",
        "applications.reviews_empty": "Buundooyinka iyo faallooyinka eegayaasha ayaa halkan ka muuqan doona",
        "applications.eligibility_responses": "Jawaabaha xaq u yeelashada",
        "applications.scores_empty": "Buundooyinku waxay muuqan doonaan ka dib qiimeynta AI iyo eegista",
        "applications.score_overview": "Dulmar buundooyinka",
        "applications.score.ai": "Buundada AI",
        "applications.score.human": "Aadame",
        "applications.score.final": "Ugu dambeysa",
        "applications.word_count": "erayo {n}",
        "compliance.due_label": "Wakhtiga: {date}",
        "compliance.status_at_risk": "halis ku jira",
        "compliance.no_reports_yet": "Weli ma jiraan warbixino deeqdan.",
    },
}

for lang, additions in KEYS.items():
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lang}: +{added}")
