"""Phase 24-25 — i18n keys for chat thread + cohort + PWA + share strings.

Focuses on the most user-visible strings. The remaining hardcoded
strings continue to fall through to English at runtime per Kuja's
inline-fallback convention.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"


KEYS = {
    "en": {
        # Phase 24E — AI chat panel + /chat page
        "nav.chat": "Chat with Kuja",
        "chat.page.title": "Chat with Kuja",
        "chat.page.subtitle": "A real conversation — ask follow-ups, refine in place, compare across turns. Each chat is private to you and tagged for cost. Tap reset anytime to start fresh.",
        "chat.header.eyebrow": "Kuja chat",
        "chat.header.new": "New conversation",
        "chat.header.scope_global": "global",
        "chat.action.reset": "Reset",
        "chat.action.send": "Send",
        "chat.placeholder": "Ask, refine, follow up…  (Enter to send · Shift+Enter for newline)",
        "chat.opening": "Opening thread…",
        "chat.empty.title": "Start a real conversation",
        "chat.empty.hint": "Ask follow-ups. Compare across turns. Revise in place. Kuja remembers this thread for as long as you want it to.",
        "chat.thinking": "thinking…",
        "chat.error.unavailable": "[The AI is unavailable for a moment — try again shortly.]",
        "chat.error.network": "[Network blip — please retry.]",
        "chat.confirm.reset": "Clear this conversation? The thread starts fresh.",

        # Phase 24D — PWA install banner + share button
        "pwa.install.title": "Install Kuja for faster access",
        "pwa.install.body": "Adds an icon to your home screen. Opens straight to today's priorities, works briefly offline.",
        "pwa.install.cta": "Install",
        "pwa.install.dismiss": "Not now",
        "share.button": "Share",
        "share.label_profile": "Share profile",
        "share.copied": "Copied",
        "share.toast_success": "Link copied",
        "share.toast_failed": "Could not copy link",

        # Phase 24C — DonorCohortCard
        "cohort.eyebrow": "Donor cohort",
        "cohort.title": "Portfolio quality vs cohort",
        "cohort.subtitle": "Anonymous comparison of the NGOs you fund vs the NGOs other donors fund — capacity, diversity, and grantee reporting compliance.",
        "cohort.loading": "Loading cohort analytics…",
        "cohort.verdict.above": "Above cohort",
        "cohort.verdict.around": "On par",
        "cohort.verdict.below": "Below cohort",
        "cohort.row.you": "You",
        "cohort.row.cohort": "Cohort",
        "cohort.sparse": "Only {n} other donor(s) on the platform — not enough yet to fairly compare. As more grant-makers join, this card fills in.",
        "cohort.empty": "Once you've awarded a couple of grants, we'll show how your portfolio compares to the {n} other donor(s) on this platform across capacity, diversity, and grantee reporting compliance.",
        "cohort.footer": "Medians only · no donor or NGO identities exposed · portfolio size: {n}",
    },
    "fr": {
        "nav.chat": "Discuter avec Kuja",
        "chat.page.title": "Discuter avec Kuja",
        "chat.page.subtitle": "Une vraie conversation — posez des questions de suivi, affinez sur place, comparez d'un tour à l'autre.",
        "chat.header.eyebrow": "Chat Kuja",
        "chat.header.new": "Nouvelle conversation",
        "chat.header.scope_global": "global",
        "chat.action.reset": "Réinitialiser",
        "chat.action.send": "Envoyer",
        "chat.placeholder": "Demandez, affinez, poursuivez…  (Entrée pour envoyer · Maj+Entrée pour une nouvelle ligne)",
        "chat.opening": "Ouverture du fil…",
        "chat.empty.title": "Commencez une vraie conversation",
        "chat.empty.hint": "Posez des questions. Comparez. Révisez. Kuja se souvient de ce fil aussi longtemps que vous le souhaitez.",
        "chat.thinking": "réflexion…",
        "chat.error.unavailable": "[L'IA est indisponible un instant — réessayez bientôt.]",
        "chat.error.network": "[Problème réseau — réessayez s'il vous plaît.]",
        "chat.confirm.reset": "Effacer cette conversation ? Le fil recommence à zéro.",
        "pwa.install.title": "Installer Kuja pour un accès plus rapide",
        "pwa.install.body": "Ajoute une icône à votre écran d'accueil. Ouvre directement les priorités du jour, fonctionne brièvement hors ligne.",
        "pwa.install.cta": "Installer",
        "pwa.install.dismiss": "Pas maintenant",
        "share.button": "Partager",
        "share.label_profile": "Partager le profil",
        "share.copied": "Copié",
        "share.toast_success": "Lien copié",
        "share.toast_failed": "Impossible de copier le lien",
        "cohort.eyebrow": "Cohorte de donateurs",
        "cohort.title": "Qualité du portefeuille vs cohorte",
        "cohort.subtitle": "Comparaison anonyme des ONG que vous financez par rapport à celles que financent les autres donateurs.",
        "cohort.loading": "Chargement de l'analyse de cohorte…",
        "cohort.verdict.above": "Au-dessus de la cohorte",
        "cohort.verdict.around": "Au niveau",
        "cohort.verdict.below": "En dessous de la cohorte",
        "cohort.row.you": "Vous",
        "cohort.row.cohort": "Cohorte",
        "cohort.sparse": "Seulement {n} autre(s) donateur(s) sur la plateforme — pas encore assez pour comparer.",
        "cohort.empty": "Une fois quelques subventions accordées, nous montrerons votre comparaison à {n} autre(s) donateur(s).",
        "cohort.footer": "Médianes uniquement · aucune identité exposée · portefeuille : {n}",
    },
    "es": {
        "nav.chat": "Chatear con Kuja",
        "chat.page.title": "Chatear con Kuja",
        "chat.page.subtitle": "Una conversación real — haga preguntas de seguimiento, refine sobre la marcha, compare entre turnos.",
        "chat.header.eyebrow": "Chat Kuja",
        "chat.header.new": "Nueva conversación",
        "chat.header.scope_global": "global",
        "chat.action.reset": "Reiniciar",
        "chat.action.send": "Enviar",
        "chat.placeholder": "Pregunte, refine, continúe…  (Enter para enviar · Shift+Enter para nueva línea)",
        "chat.opening": "Abriendo hilo…",
        "chat.empty.title": "Comienza una conversación real",
        "chat.empty.hint": "Haga preguntas. Compare entre turnos. Revise en el lugar. Kuja recuerda este hilo todo el tiempo que quiera.",
        "chat.thinking": "pensando…",
        "chat.error.unavailable": "[La IA no está disponible por un momento — inténtelo de nuevo en breve.]",
        "chat.error.network": "[Problema de red — por favor reintente.]",
        "chat.confirm.reset": "¿Borrar esta conversación? El hilo empieza de nuevo.",
        "pwa.install.title": "Instalar Kuja para acceso más rápido",
        "pwa.install.body": "Añade un icono a su pantalla de inicio. Abre directamente las prioridades del día, funciona brevemente sin conexión.",
        "pwa.install.cta": "Instalar",
        "pwa.install.dismiss": "Ahora no",
        "share.button": "Compartir",
        "share.label_profile": "Compartir perfil",
        "share.copied": "Copiado",
        "share.toast_success": "Enlace copiado",
        "share.toast_failed": "No se pudo copiar el enlace",
        "cohort.eyebrow": "Cohorte de donantes",
        "cohort.title": "Calidad de cartera vs cohorte",
        "cohort.subtitle": "Comparación anónima de las ONG que financia vs las que financian otros donantes.",
        "cohort.loading": "Cargando análisis de cohorte…",
        "cohort.verdict.above": "Por encima de la cohorte",
        "cohort.verdict.around": "Al nivel",
        "cohort.verdict.below": "Por debajo de la cohorte",
        "cohort.row.you": "Usted",
        "cohort.row.cohort": "Cohorte",
        "cohort.sparse": "Solo {n} otro(s) donante(s) en la plataforma — todavía no es suficiente para comparar.",
        "cohort.empty": "Una vez otorgadas algunas subvenciones, mostraremos la comparación con {n} otro(s) donante(s).",
        "cohort.footer": "Solo medianas · no se exponen identidades · cartera: {n}",
    },
    "ar": {
        "nav.chat": "الدردشة مع كوجا",
        "chat.page.title": "الدردشة مع كوجا",
        "chat.page.subtitle": "محادثة حقيقية — اطرح أسئلة متابعة، حسّن في مكانها، قارن عبر الأدوار.",
        "chat.header.eyebrow": "دردشة كوجا",
        "chat.header.new": "محادثة جديدة",
        "chat.header.scope_global": "عام",
        "chat.action.reset": "إعادة تعيين",
        "chat.action.send": "إرسال",
        "chat.placeholder": "اسأل، حسّن، تابع…  (Enter للإرسال · Shift+Enter لسطر جديد)",
        "chat.opening": "فتح المحادثة…",
        "chat.empty.title": "ابدأ محادثة حقيقية",
        "chat.empty.hint": "اطرح أسئلة متابعة. قارن عبر الأدوار. راجع في مكانها. تتذكر كوجا هذه المحادثة طالما أردت.",
        "chat.thinking": "يفكر…",
        "chat.error.unavailable": "[الذكاء الاصطناعي غير متاح للحظة — حاول مرة أخرى قريبًا.]",
        "chat.error.network": "[خلل في الشبكة — يرجى إعادة المحاولة.]",
        "chat.confirm.reset": "مسح هذه المحادثة؟ يبدأ الحوار من جديد.",
        "pwa.install.title": "ثبّت كوجا للوصول الأسرع",
        "pwa.install.body": "يضيف أيقونة إلى شاشتك الرئيسية. يفتح مباشرة على أولويات اليوم.",
        "pwa.install.cta": "تثبيت",
        "pwa.install.dismiss": "ليس الآن",
        "share.button": "مشاركة",
        "share.label_profile": "مشاركة الملف الشخصي",
        "share.copied": "تم النسخ",
        "share.toast_success": "تم نسخ الرابط",
        "share.toast_failed": "تعذر نسخ الرابط",
        "cohort.eyebrow": "مجموعة المانحين",
        "cohort.title": "جودة المحفظة مقابل المجموعة",
        "cohort.subtitle": "مقارنة مجهولة للمنظمات التي تمولها مقابل التي يمولها مانحون آخرون.",
        "cohort.loading": "تحميل تحليل المجموعة…",
        "cohort.verdict.above": "فوق المجموعة",
        "cohort.verdict.around": "على المستوى",
        "cohort.verdict.below": "تحت المجموعة",
        "cohort.row.you": "أنت",
        "cohort.row.cohort": "المجموعة",
        "cohort.sparse": "فقط {n} مانح آخر على المنصة — ليس كافيًا بعد للمقارنة.",
        "cohort.empty": "بمجرد منح بعض المنح، سنعرض مقارنة محفظتك مع {n} مانح آخر.",
        "cohort.footer": "متوسطات فقط · لا تظهر هويات · حجم المحفظة: {n}",
    },
    "sw": {
        "nav.chat": "Ongea na Kuja",
        "chat.page.title": "Ongea na Kuja",
        "chat.page.subtitle": "Mazungumzo halisi — uliza maswali ya kufuatilia, sahihisha papo hapo, linganisha kati ya zamu.",
        "chat.header.eyebrow": "Soga ya Kuja",
        "chat.header.new": "Mazungumzo mapya",
        "chat.header.scope_global": "kimataifa",
        "chat.action.reset": "Anza upya",
        "chat.action.send": "Tuma",
        "chat.placeholder": "Uliza, sahihisha, fuatilia…  (Enter kutuma · Shift+Enter kwa mstari mpya)",
        "chat.opening": "Inafungua mazungumzo…",
        "chat.empty.title": "Anza mazungumzo halisi",
        "chat.empty.hint": "Uliza maswali ya kufuatilia. Linganisha. Sahihisha. Kuja inakumbuka mazungumzo haya kwa muda upendao.",
        "chat.thinking": "inafikiri…",
        "chat.error.unavailable": "[AI haipatikani kwa muda — jaribu tena hivi karibuni.]",
        "chat.error.network": "[Tatizo la mtandao — tafadhali jaribu tena.]",
        "chat.confirm.reset": "Futa mazungumzo haya? Yataanza upya.",
        "pwa.install.title": "Sakinisha Kuja kwa ufikiaji wa haraka",
        "pwa.install.body": "Inaongeza aikoni kwenye skrini yako ya nyumbani. Inafungua moja kwa moja kipaumbele cha leo.",
        "pwa.install.cta": "Sakinisha",
        "pwa.install.dismiss": "Si sasa",
        "share.button": "Shiriki",
        "share.label_profile": "Shiriki wasifu",
        "share.copied": "Imenakiliwa",
        "share.toast_success": "Kiungo kimenakiliwa",
        "share.toast_failed": "Imeshindwa kunakili kiungo",
        "cohort.eyebrow": "Kundi la wafadhili",
        "cohort.title": "Ubora wa kasha vs kundi",
        "cohort.subtitle": "Ulinganishaji wa siri wa NGOs unaowafadhili dhidi ya wale wanaofadhiliwa na wafadhili wengine.",
        "cohort.loading": "Inapakia uchambuzi wa kundi…",
        "cohort.verdict.above": "Juu ya kundi",
        "cohort.verdict.around": "Kwa kiwango",
        "cohort.verdict.below": "Chini ya kundi",
        "cohort.row.you": "Wewe",
        "cohort.row.cohort": "Kundi",
        "cohort.sparse": "Mfadhili {n} tu mwingine kwenye jukwaa — hatutoshi bado kulinganisha.",
        "cohort.empty": "Mara baada ya kutoa misaada michache, tutaonyesha ulinganisho wa kasha lako na mfadhili {n} mwingine.",
        "cohort.footer": "Wastani tu · hakuna utambulisho unaofunuliwa · ukubwa wa kasha: {n}",
    },
    "so": {
        "nav.chat": "La sheekayso Kuja",
        "chat.page.title": "La sheekayso Kuja",
        "chat.page.subtitle": "Sheekaysi run ah — weydiiso su'aalo dheeraad ah, hagaaji meeshaada, isbarbar dhig wareegyada.",
        "chat.header.eyebrow": "Sheekaysi Kuja",
        "chat.header.new": "Sheekaysi cusub",
        "chat.header.scope_global": "guud",
        "chat.action.reset": "Dib u bilow",
        "chat.action.send": "Dir",
        "chat.placeholder": "Weydiiso, hagaaji, sii wad…  (Enter si aad u dirto · Shift+Enter sadar cusub)",
        "chat.opening": "Furista sheekaysiga…",
        "chat.empty.title": "Bilow sheekaysi run ah",
        "chat.empty.hint": "Weydiiso su'aalo dheeraad ah. Isbarbar dhig. Hagaaji. Kuja way xasuusataa sheekaysigan illaa aad rabto.",
        "chat.thinking": "feker…",
        "chat.error.unavailable": "[AI ma diyaarsana daqiiqad — isku day mar dambe.]",
        "chat.error.network": "[Khalad shabakad — fadlan isku day mar kale.]",
        "chat.confirm.reset": "Tirtir sheekaysigan? Sheekaysiga wuxuu bilaabmayaa cusub.",
        "pwa.install.title": "Rakib Kuja si aad u helo si dhaqso ah",
        "pwa.install.body": "Wuxuu ku darayaa astaan ​​shaashaddaada hoyga. Si toos ah ayuu ugu furayaa mudnaanta maanta.",
        "pwa.install.cta": "Rakib",
        "pwa.install.dismiss": "Maya hadda",
        "share.button": "Wadaag",
        "share.label_profile": "Wadaag astaan",
        "share.copied": "Waa la koobiyay",
        "share.toast_success": "Linkiga waa la koobiyay",
        "share.toast_failed": "Waxaan awoodi kari waayay inaan koobiyo linkiga",
        "cohort.eyebrow": "Koox deeq-bixiye",
        "cohort.title": "Tayada xafiiska vs koox",
        "cohort.subtitle": "Isbarbardhig qarsoodi ah oo NGO-yada aad maalgeliso vs kuwa ay maalgeliyaan deeq-bixiyayaal kale.",
        "cohort.loading": "Soo dejinta falanqaynta kooxda…",
        "cohort.verdict.above": "Kor ka sarreeya kooxda",
        "cohort.verdict.around": "Heer ahaan",
        "cohort.verdict.below": "Hoos ka jirta kooxda",
        "cohort.row.you": "Adiga",
        "cohort.row.cohort": "Kooxda",
        "cohort.sparse": "Kaliya {n} deeq-bixiye kale oo madasha — kuma filna in la isbarbar dhigo.",
        "cohort.empty": "Marka aad bixiso dhowr deeqood, waxaan tusi doonnaa isbarbardhiga xafiiskaaga iyo {n} deeq-bixiye kale.",
        "cohort.footer": "Dhexdhexaad oo keliya · ma jirto aqoonsi la muujiyay · cabbirka xafiiska: {n}",
    },
}


def main():
    for locale, keys in KEYS.items():
        path = ROOT / f"{locale}.json"
        if not path.exists():
            print(f"  [skip] {locale}.json not found")
            continue
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        added = []
        updated = []
        for k, v in keys.items():
            if k not in data:
                added.append(k)
            elif data[k] != v:
                updated.append(k)
            data[k] = v
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
            f.write("\n")
        print(f"  {locale}.json: +{len(added)} new, ~{len(updated)} updated")


if __name__ == "__main__":
    main()
