"""Phase 18-22 — i18n keys for newer component strings.

~50 keys per locale × 6 locales = 300 entries. Focuses on the most
user-visible labels (cards titles, action buttons, status verdicts).
Uncovered hardcoded strings will fall through to English at runtime.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"


KEYS = {
    "en": {
        # Phase 18A — TrustGapInsightsCard
        "trust_gap.eyebrow": "Close the gap",
        "trust_gap.title": "How to lift your trust score",
        "trust_gap.subtitle": "AI reads your two pillars + sub-components and prioritises the highest-leverage actions.",
        "trust_gap.projection": "Projection",
        "trust_gap.try_next": "Try next",
        "trust_gap.computing": "Computing gap analysis…",
        "trust_gap.effort.low": "Low effort",
        "trust_gap.effort.medium": "Medium effort",
        "trust_gap.effort.high": "High effort",
        "trust_gap.disclaimer": "Lift estimates are AI projections, not guarantees. Quick wins first.",

        # Phase 18B — DonorProfilePage
        "donor_profile.back": "Back to organizations",
        "donor_profile.portfolio_snapshot": "Portfolio snapshot",
        "donor_profile.open_grants": "Open grants",
        "donor_profile.committed": "Committed",
        "donor_profile.decision_speed": "Decision speed",
        "donor_profile.decline_rate": "Decline rate",
        "donor_profile.active_sectors": "Active sectors",
        "donor_profile.active_countries": "Active countries",
        "donor_profile.reporting_burden": "Reporting burden",
        "donor_profile.see_grants": "See grants",
        "donor_profile.no_sectors": "No sectors tagged on grants yet.",
        "donor_profile.no_countries": "No countries tagged on grants yet.",
        "donor_profile.sparse_explainer": "This donor has fewer than 3 decided applications on the platform — not enough yet to fairly characterise their decision pattern.",

        # Phase 19C — NGOSummaryPage
        "ngo_summary.trust_at_glance": "Trust at a glance",
        "ngo_summary.delivery_snapshot": "Delivery snapshot",
        "ngo_summary.awarded": "Awarded",
        "ngo_summary.active": "Active",
        "ngo_summary.reports": "Reports",
        "ngo_summary.sectors": "Sectors",
        "ngo_summary.geographic_footprint": "Geographic footprint",
        "ngo_summary.no_sectors": "No sectors listed.",
        "ngo_summary.no_geographies": "No geographies listed.",
        "ngo_summary.privacy_footer": "Aggregate data only · individual applications and grant amounts never appear here · published by the NGO itself.",
        "ngo_summary.not_published_title": "This NGO hasn't opted into a public summary",
        "ngo_summary.not_published_hint": "The NGO can choose to publish a summary from their organisation profile.",

        # Phase 20A — ApplicationTimeline
        "timeline.eyebrow": "Application activity",
        "timeline.title": "Everything that's happened",
        "timeline.event_count": "{n} event(s)",
        "timeline.empty": "No activity recorded yet. Events will appear here as the application progresses.",
        "timeline.loading": "Loading timeline…",

        # Phase 20B — ReviewerBriefingCard
        "reviewer_briefing.eyebrow": "Reviewer briefing",
        "reviewer_briefing.title": "What to probe before scoring",
        "reviewer_briefing.subtitle": "AI reads the submission + grant criteria and surfaces the 3–5 questions most worth testing. Helps panel consistency without dictating verdicts.",
        "reviewer_briefing.computing": "Reading the submission…",
        "reviewer_briefing.probe_these": "Probe these in your review",
        "reviewer_briefing.sparse": "Application is too sparse to generate a useful briefing yet. Wait for the NGO to fill in more before scoring.",
        "reviewer_briefing.unavailable": "Briefing is unavailable right now. You can still score manually.",

        # Phase 20C — ApplicationMessageThread
        "message_thread.eyebrow": "Conversation",
        "message_thread.title": "Donor & NGO thread",
        "message_thread.loading": "Loading conversation…",
        "message_thread.empty": "No messages yet. Start the conversation below — both sides will see this thread.",
        "message_thread.placeholder": "Ask a question, share a clarification, or post a quick update… (4,000 chars max)",
        "message_thread.send_hint": "Ctrl/Cmd + Enter to send. Mention with @email-username.",
        "message_thread.post": "Post",

        # Phase 21A — PanelCalibrationCard
        "calibration.eyebrow": "Panel calibration",
        "calibration.status.tight": "Tight panel",
        "calibration.status.tight_hint": "Reviewers agree within 8 points.",
        "calibration.status.normal": "Normal variance",
        "calibration.status.normal_hint": "Reviewers within 20 points — typical for human review.",
        "calibration.status.divergent": "Divergent panel",
        "calibration.status.divergent_hint": "Spread > 20 points — consider a tie-breaking review.",
        "calibration.action_needed": "Action recommended: the panel disagrees by more than 20 points. Ask the outlier reviewer(s) for their rationale, or assign a third reviewer to break the tie.",

        # Phase 21B — GrantBroadcastDialog
        "broadcast.title": "Broadcast to applicants",
        "broadcast.description": "Send one message to every NGO with an application on this grant. Recipients get it via their preferred channels (in-app + email + SMS).",
        "broadcast.subject_label": "Subject",
        "broadcast.subject_placeholder": "e.g. Deadline extended by 5 days",
        "broadcast.body_label": "Message",
        "broadcast.body_placeholder": "Plain text. Be explicit — recipients won't see attached docs.",
        "broadcast.audience_label": "Audience",
        "broadcast.audience.all": "All applicants",
        "broadcast.audience.drafts": "Drafts only",
        "broadcast.audience.submitted": "Submitted only",
        "broadcast.send_button": "Send broadcast",
        "broadcast.sent_title": "Broadcast sent.",

        # Phase 22A — ScoreBreakdownCard
        "score_breakdown.eyebrow": "Score breakdown",
        "score_breakdown.title": "How your overall score is built",
        "score_breakdown.strongest": "Strongest",
        "score_breakdown.weakest": "Weakest",
        "score_breakdown.not_scored": "not scored",
        "score_breakdown.weight_label": "{n}% weight",
    },

    # ----- Arabic
    "ar": {
        "trust_gap.eyebrow": "أغلق الفجوة",
        "trust_gap.title": "كيف ترفع درجة الثقة",
        "trust_gap.subtitle": "يقرأ الذكاء الاصطناعي ركيزتيك والمكونات الفرعية ويرتّب الإجراءات الأعلى تأثيراً.",
        "trust_gap.projection": "التوقع",
        "trust_gap.try_next": "جرّب التالي",
        "trust_gap.computing": "جارٍ حساب تحليل الفجوة…",
        "trust_gap.effort.low": "جهد منخفض",
        "trust_gap.effort.medium": "جهد متوسط",
        "trust_gap.effort.high": "جهد عالٍ",
        "trust_gap.disclaimer": "التقديرات توقعات AI وليست ضمانات. ابدأ بالمكاسب السريعة.",
        "donor_profile.back": "العودة إلى المنظمات",
        "donor_profile.portfolio_snapshot": "لمحة المحفظة",
        "donor_profile.open_grants": "المنح المفتوحة",
        "donor_profile.committed": "ملتزَم بها",
        "donor_profile.decision_speed": "سرعة القرار",
        "donor_profile.decline_rate": "معدّل الرفض",
        "donor_profile.active_sectors": "القطاعات النشطة",
        "donor_profile.active_countries": "البلدان النشطة",
        "donor_profile.reporting_burden": "عبء التقارير",
        "donor_profile.see_grants": "عرض المنح",
        "donor_profile.no_sectors": "لا توجد قطاعات مرتبطة بالمنح بعد.",
        "donor_profile.no_countries": "لا توجد بلدان مرتبطة بالمنح بعد.",
        "donor_profile.sparse_explainer": "لدى هذا المانح أقل من 3 طلبات مفصول فيها على المنصة — العيّنة صغيرة جداً.",
        "ngo_summary.trust_at_glance": "الثقة بنظرة سريعة",
        "ngo_summary.delivery_snapshot": "لمحة التسليم",
        "ngo_summary.awarded": "ممنوحة",
        "ngo_summary.active": "نشطة",
        "ngo_summary.reports": "تقارير",
        "ngo_summary.sectors": "القطاعات",
        "ngo_summary.geographic_footprint": "البصمة الجغرافية",
        "ngo_summary.no_sectors": "لا توجد قطاعات مدرجة.",
        "ngo_summary.no_geographies": "لا توجد جغرافيات مدرجة.",
        "ngo_summary.privacy_footer": "بيانات إجمالية فقط · لا تظهر الطلبات الفردية أو مبالغ المنح هنا · المنظمة نشرته بنفسها.",
        "ngo_summary.not_published_title": "هذه المنظمة لم تختر نشر ملخص عام",
        "ngo_summary.not_published_hint": "يمكن للمنظمة اختيار نشر ملخص من ملف منظمتها.",
        "timeline.eyebrow": "نشاط الطلب",
        "timeline.title": "كل ما حدث",
        "timeline.event_count": "{n} حدث",
        "timeline.empty": "لم يُسجَّل أي نشاط بعد. ستظهر الأحداث هنا مع تقدم الطلب.",
        "timeline.loading": "جارٍ تحميل المسار الزمني…",
        "reviewer_briefing.eyebrow": "إيجاز المراجع",
        "reviewer_briefing.title": "ما يجب التحقق منه قبل التسجيل",
        "reviewer_briefing.subtitle": "يقرأ AI الطلب + المعايير ويُبرز الأسئلة الثلاث إلى الخمس الأكثر أهمية. يساعد على اتساق اللجنة دون فرض الأحكام.",
        "reviewer_briefing.computing": "جارٍ قراءة الطلب…",
        "reviewer_briefing.probe_these": "تحقّق من هذه في مراجعتك",
        "reviewer_briefing.sparse": "الطلب أقل من أن يولّد إيجازاً مفيداً. انتظر حتى تكتمل بياناته.",
        "reviewer_briefing.unavailable": "الإيجاز غير متاح حالياً. يمكنك التسجيل يدوياً.",
        "message_thread.eyebrow": "المحادثة",
        "message_thread.title": "خيط المانح والمنظمة",
        "message_thread.loading": "جارٍ تحميل المحادثة…",
        "message_thread.empty": "لا توجد رسائل بعد. ابدأ المحادثة أدناه — سيرى الطرفان هذا الخيط.",
        "message_thread.placeholder": "اطرح سؤالاً أو شارك توضيحاً أو أضف تحديثاً سريعاً… (حتى 4000 حرف)",
        "message_thread.send_hint": "Ctrl/Cmd + Enter للإرسال. أَشِر إلى مستخدم بـ @username.",
        "message_thread.post": "إرسال",
        "calibration.eyebrow": "معايرة اللجنة",
        "calibration.status.tight": "لجنة متّفقة",
        "calibration.status.tight_hint": "المراجعون متفقون في حدود 8 نقاط.",
        "calibration.status.normal": "تباين طبيعي",
        "calibration.status.normal_hint": "المراجعون في حدود 20 نقطة — طبيعي للمراجعة البشرية.",
        "calibration.status.divergent": "لجنة متباينة",
        "calibration.status.divergent_hint": "الفارق > 20 نقطة — فكّر بمراجعة فاصلة.",
        "calibration.action_needed": "إجراء موصى به: اللجنة متباينة بأكثر من 20 نقطة. اطلب من المراجع(ين) الشاذّين تبرير تقييمهم أو عيّن مراجعاً ثالثاً لكسر التعادل.",
        "broadcast.title": "بثّ للمتقدمين",
        "broadcast.description": "أرسل رسالة واحدة لكل منظمة لديها طلب على هذه المنحة. يصل عبر القنوات المفضّلة للمستلم.",
        "broadcast.subject_label": "الموضوع",
        "broadcast.subject_placeholder": "مثال: تمديد الموعد النهائي 5 أيام",
        "broadcast.body_label": "الرسالة",
        "broadcast.body_placeholder": "نص عادي. كن صريحاً — لن يرى المستلمون المرفقات.",
        "broadcast.audience_label": "الجمهور",
        "broadcast.audience.all": "كل المتقدمين",
        "broadcast.audience.drafts": "المسودّات فقط",
        "broadcast.audience.submitted": "المُقدَّمة فقط",
        "broadcast.send_button": "إرسال البث",
        "broadcast.sent_title": "تم إرسال البث.",
        "score_breakdown.eyebrow": "تفصيل الدرجة",
        "score_breakdown.title": "كيف تُبنى درجتك الإجمالية",
        "score_breakdown.strongest": "الأقوى",
        "score_breakdown.weakest": "الأضعف",
        "score_breakdown.not_scored": "غير مُقَيَّم",
        "score_breakdown.weight_label": "{n}% وزن",
    },

    # ----- Swahili
    "sw": {
        "trust_gap.eyebrow": "Funga pengo",
        "trust_gap.title": "Jinsi ya kuinua alama yako ya uaminifu",
        "trust_gap.subtitle": "AI inasoma nguzo zako mbili na vipengele vyake na kuweka kipaumbele kwa hatua zenye athari kubwa zaidi.",
        "trust_gap.projection": "Makadirio",
        "trust_gap.try_next": "Jaribu inayofuata",
        "trust_gap.computing": "Inahesabu uchambuzi…",
        "trust_gap.effort.low": "Juhudi ndogo",
        "trust_gap.effort.medium": "Juhudi ya kati",
        "trust_gap.effort.high": "Juhudi kubwa",
        "trust_gap.disclaimer": "Makadirio ni utabiri wa AI, si dhamana. Anza na ushindi wa haraka.",
        "donor_profile.back": "Rudi kwa mashirika",
        "donor_profile.portfolio_snapshot": "Muhtasari wa kundi",
        "donor_profile.open_grants": "Ruzuku zilizofunguliwa",
        "donor_profile.committed": "Imeahidiwa",
        "donor_profile.decision_speed": "Kasi ya uamuzi",
        "donor_profile.decline_rate": "Kiwango cha kukataa",
        "donor_profile.active_sectors": "Sekta zinazofanya kazi",
        "donor_profile.active_countries": "Nchi zinazofanya kazi",
        "donor_profile.reporting_burden": "Mzigo wa kuripoti",
        "donor_profile.see_grants": "Tazama ruzuku",
        "donor_profile.no_sectors": "Hakuna sekta zilizotambulishwa kwenye ruzuku bado.",
        "donor_profile.no_countries": "Hakuna nchi zilizotambulishwa kwenye ruzuku bado.",
        "donor_profile.sparse_explainer": "Mfadhili huyu ana chini ya maombi 3 yaliyoamuliwa kwenye jukwaa — sampuli ndogo sana kutoa muhtasari wa haki.",
        "ngo_summary.trust_at_glance": "Uaminifu kwa muhtasari",
        "ngo_summary.delivery_snapshot": "Muhtasari wa utoaji",
        "ngo_summary.awarded": "Iliyopewa",
        "ngo_summary.active": "Hai",
        "ngo_summary.reports": "Ripoti",
        "ngo_summary.sectors": "Sekta",
        "ngo_summary.geographic_footprint": "Eneo la kijiografia",
        "ngo_summary.no_sectors": "Hakuna sekta zilizoorodheshwa.",
        "ngo_summary.no_geographies": "Hakuna jiografia zilizoorodheshwa.",
        "ngo_summary.privacy_footer": "Data ya jumla tu · maombi binafsi na kiasi cha ruzuku havitokei hapa · imechapishwa na NGO yenyewe.",
        "ngo_summary.not_published_title": "NGO hii haijachagua kuchapisha muhtasari wa umma",
        "ngo_summary.not_published_hint": "NGO inaweza kuchagua kuchapisha muhtasari kutoka kwa wasifu wa shirika lao.",
        "timeline.eyebrow": "Shughuli ya maombi",
        "timeline.title": "Kila kilichotokea",
        "timeline.event_count": "Matukio {n}",
        "timeline.empty": "Hakuna shughuli iliyorekodiwa bado. Matukio yatatokea hapa maombi yanapoendelea.",
        "timeline.loading": "Inapakia ratiba…",
        "reviewer_briefing.eyebrow": "Maelekezo ya mkaguzi",
        "reviewer_briefing.title": "Cha kuchunguza kabla ya kupiga alama",
        "reviewer_briefing.subtitle": "AI inasoma uwasilishaji + vigezo na kuibua maswali 3-5 muhimu zaidi ya kupima. Husaidia ushirikiano wa jopo bila kuamuru hukumu.",
        "reviewer_briefing.computing": "Inasoma uwasilishaji…",
        "reviewer_briefing.probe_these": "Chunguza hizi katika ukaguzi wako",
        "reviewer_briefing.sparse": "Maombi ni mafupi sana kutoa muelekezo wenye manufaa. Subiri NGO ijaze zaidi.",
        "reviewer_briefing.unavailable": "Maelekezo hayapatikani kwa sasa. Bado unaweza kupiga alama mwenyewe.",
        "message_thread.eyebrow": "Mazungumzo",
        "message_thread.title": "Mhimili wa mfadhili na NGO",
        "message_thread.loading": "Inapakia mazungumzo…",
        "message_thread.empty": "Hakuna ujumbe bado. Anzisha mazungumzo hapa chini — pande zote mbili zitaona huu mhimili.",
        "message_thread.placeholder": "Uliza swali, shiriki ufafanuzi au toa sasisho la haraka… (herufi 4,000 max)",
        "message_thread.send_hint": "Ctrl/Cmd + Enter kutuma. Taja kwa @username.",
        "message_thread.post": "Chapisha",
        "calibration.eyebrow": "Mlinganisho wa jopo",
        "calibration.status.tight": "Jopo lililo na maoni yanayofanana",
        "calibration.status.tight_hint": "Wakaguzi wanakubaliana ndani ya pointi 8.",
        "calibration.status.normal": "Tofauti ya kawaida",
        "calibration.status.normal_hint": "Wakaguzi ndani ya pointi 20 — kawaida kwa ukaguzi wa kibinadamu.",
        "calibration.status.divergent": "Jopo lililotofautiana",
        "calibration.status.divergent_hint": "Tofauti > pointi 20 — fikiria ukaguzi wa kuvunja sare.",
        "calibration.action_needed": "Hatua inashauriwa: jopo halikubaliani kwa zaidi ya pointi 20. Uliza mkaguzi/wakaguzi tofauti kueleza, au teua mkaguzi wa tatu.",
        "broadcast.title": "Tangaza kwa waombaji",
        "broadcast.description": "Tuma ujumbe mmoja kwa kila NGO yenye maombi kwenye ruzuku hii. Wapokeaji watapata kupitia njia zao zinazopendelewa.",
        "broadcast.subject_label": "Mada",
        "broadcast.subject_placeholder": "k.m. Tarehe ya mwisho imepanuliwa siku 5",
        "broadcast.body_label": "Ujumbe",
        "broadcast.body_placeholder": "Maandishi tu. Kuwa wazi — wapokeaji hawataona viambatisho.",
        "broadcast.audience_label": "Hadhira",
        "broadcast.audience.all": "Waombaji wote",
        "broadcast.audience.drafts": "Rasimu tu",
        "broadcast.audience.submitted": "Zilizowasilishwa tu",
        "broadcast.send_button": "Tuma tangazo",
        "broadcast.sent_title": "Tangazo limetumwa.",
        "score_breakdown.eyebrow": "Mchanganuo wa alama",
        "score_breakdown.title": "Jinsi alama yako kuu inavyojengwa",
        "score_breakdown.strongest": "Imara zaidi",
        "score_breakdown.weakest": "Dhaifu zaidi",
        "score_breakdown.not_scored": "haijapigwa alama",
        "score_breakdown.weight_label": "Uzito {n}%",
    },

    # ----- French
    "fr": {
        "trust_gap.eyebrow": "Combler l'écart",
        "trust_gap.title": "Comment relever votre score de confiance",
        "trust_gap.subtitle": "L'IA lit vos deux piliers + sous-composants et priorise les actions à plus fort levier.",
        "trust_gap.projection": "Projection",
        "trust_gap.try_next": "Essayez ensuite",
        "trust_gap.computing": "Calcul de l'analyse d'écart…",
        "trust_gap.effort.low": "Effort faible",
        "trust_gap.effort.medium": "Effort moyen",
        "trust_gap.effort.high": "Effort élevé",
        "trust_gap.disclaimer": "Les estimations sont des projections IA, pas des garanties. Gains rapides d'abord.",
        "donor_profile.back": "Retour aux organisations",
        "donor_profile.portfolio_snapshot": "Aperçu du portefeuille",
        "donor_profile.open_grants": "Subventions ouvertes",
        "donor_profile.committed": "Engagés",
        "donor_profile.decision_speed": "Vitesse de décision",
        "donor_profile.decline_rate": "Taux de refus",
        "donor_profile.active_sectors": "Secteurs actifs",
        "donor_profile.active_countries": "Pays actifs",
        "donor_profile.reporting_burden": "Charge de reporting",
        "donor_profile.see_grants": "Voir les subventions",
        "donor_profile.no_sectors": "Aucun secteur tagué sur les subventions.",
        "donor_profile.no_countries": "Aucun pays tagué sur les subventions.",
        "donor_profile.sparse_explainer": "Ce bailleur a moins de 3 candidatures décidées — échantillon trop petit pour caractériser ses décisions équitablement.",
        "ngo_summary.trust_at_glance": "La confiance en un coup d'œil",
        "ngo_summary.delivery_snapshot": "Aperçu de livraison",
        "ngo_summary.awarded": "Attribuées",
        "ngo_summary.active": "Actives",
        "ngo_summary.reports": "Rapports",
        "ngo_summary.sectors": "Secteurs",
        "ngo_summary.geographic_footprint": "Empreinte géographique",
        "ngo_summary.no_sectors": "Aucun secteur listé.",
        "ngo_summary.no_geographies": "Aucune géographie listée.",
        "ngo_summary.privacy_footer": "Données agrégées uniquement · les candidatures individuelles et montants n'apparaissent jamais ici · publié par l'ONG elle-même.",
        "ngo_summary.not_published_title": "Cette ONG n'a pas opté pour un résumé public",
        "ngo_summary.not_published_hint": "L'ONG peut choisir de publier un résumé depuis son profil d'organisation.",
        "timeline.eyebrow": "Activité de la candidature",
        "timeline.title": "Tout ce qui s'est passé",
        "timeline.event_count": "{n} événement(s)",
        "timeline.empty": "Aucune activité enregistrée. Les événements apparaîtront ici au fil de la candidature.",
        "timeline.loading": "Chargement de la chronologie…",
        "reviewer_briefing.eyebrow": "Briefing du relecteur",
        "reviewer_briefing.title": "Ce qu'il faut sonder avant de noter",
        "reviewer_briefing.subtitle": "L'IA lit la candidature + critères et fait remonter les 3-5 questions à tester. Aide la cohérence du panel sans dicter les verdicts.",
        "reviewer_briefing.computing": "Lecture de la candidature…",
        "reviewer_briefing.probe_these": "Sondez ceci dans votre relecture",
        "reviewer_briefing.sparse": "La candidature est trop éparse pour un briefing utile. Attendez que l'ONG en remplisse plus.",
        "reviewer_briefing.unavailable": "Briefing indisponible. Vous pouvez noter manuellement.",
        "message_thread.eyebrow": "Conversation",
        "message_thread.title": "Fil bailleur ↔ ONG",
        "message_thread.loading": "Chargement de la conversation…",
        "message_thread.empty": "Aucun message. Lancez la conversation ci-dessous — les deux côtés verront ce fil.",
        "message_thread.placeholder": "Posez une question, partagez une clarification ou une mise à jour rapide… (4 000 caractères max)",
        "message_thread.send_hint": "Ctrl/Cmd + Entrée pour envoyer. Mentionnez avec @nom.",
        "message_thread.post": "Publier",
        "calibration.eyebrow": "Calibration du panel",
        "calibration.status.tight": "Panel resserré",
        "calibration.status.tight_hint": "Les relecteurs s'accordent à 8 points près.",
        "calibration.status.normal": "Variance normale",
        "calibration.status.normal_hint": "Relecteurs à 20 points près — typique d'une relecture humaine.",
        "calibration.status.divergent": "Panel divergent",
        "calibration.status.divergent_hint": "Écart > 20 points — envisagez une relecture d'arbitrage.",
        "calibration.action_needed": "Action recommandée : le panel diverge de plus de 20 points. Demandez la rationale aux relecteurs atypiques ou ajoutez un troisième relecteur.",
        "broadcast.title": "Diffusion aux candidats",
        "broadcast.description": "Envoyez un message à chaque ONG ayant une candidature sur cette subvention. Reçu via leurs canaux préférés.",
        "broadcast.subject_label": "Objet",
        "broadcast.subject_placeholder": "ex : Date limite prolongée de 5 jours",
        "broadcast.body_label": "Message",
        "broadcast.body_placeholder": "Texte simple. Soyez explicite — les destinataires ne verront pas les pièces jointes.",
        "broadcast.audience_label": "Public",
        "broadcast.audience.all": "Tous les candidats",
        "broadcast.audience.drafts": "Brouillons seulement",
        "broadcast.audience.submitted": "Soumises seulement",
        "broadcast.send_button": "Envoyer la diffusion",
        "broadcast.sent_title": "Diffusion envoyée.",
        "score_breakdown.eyebrow": "Décomposition du score",
        "score_breakdown.title": "Comment votre score global est construit",
        "score_breakdown.strongest": "Le plus fort",
        "score_breakdown.weakest": "Le plus faible",
        "score_breakdown.not_scored": "non noté",
        "score_breakdown.weight_label": "Poids {n}%",
    },

    # ----- Spanish
    "es": {
        "trust_gap.eyebrow": "Cierra la brecha",
        "trust_gap.title": "Cómo elevar tu puntaje de confianza",
        "trust_gap.subtitle": "La IA lee tus dos pilares + subcomponentes y prioriza las acciones de mayor impacto.",
        "trust_gap.projection": "Proyección",
        "trust_gap.try_next": "Prueba lo siguiente",
        "trust_gap.computing": "Calculando análisis de brechas…",
        "trust_gap.effort.low": "Esfuerzo bajo",
        "trust_gap.effort.medium": "Esfuerzo medio",
        "trust_gap.effort.high": "Esfuerzo alto",
        "trust_gap.disclaimer": "Las estimaciones son proyecciones de IA, no garantías. Primero los logros rápidos.",
        "donor_profile.back": "Volver a organizaciones",
        "donor_profile.portfolio_snapshot": "Vista del portafolio",
        "donor_profile.open_grants": "Subvenciones abiertas",
        "donor_profile.committed": "Comprometido",
        "donor_profile.decision_speed": "Velocidad de decisión",
        "donor_profile.decline_rate": "Tasa de rechazo",
        "donor_profile.active_sectors": "Sectores activos",
        "donor_profile.active_countries": "Países activos",
        "donor_profile.reporting_burden": "Carga de reporte",
        "donor_profile.see_grants": "Ver subvenciones",
        "donor_profile.no_sectors": "Aún sin sectores etiquetados en subvenciones.",
        "donor_profile.no_countries": "Aún sin países etiquetados en subvenciones.",
        "donor_profile.sparse_explainer": "Este donante tiene menos de 3 aplicaciones decididas — muestra muy pequeña aún para caracterizar sus decisiones.",
        "ngo_summary.trust_at_glance": "La confianza de un vistazo",
        "ngo_summary.delivery_snapshot": "Vista de entrega",
        "ngo_summary.awarded": "Ganadas",
        "ngo_summary.active": "Activas",
        "ngo_summary.reports": "Informes",
        "ngo_summary.sectors": "Sectores",
        "ngo_summary.geographic_footprint": "Huella geográfica",
        "ngo_summary.no_sectors": "Sin sectores listados.",
        "ngo_summary.no_geographies": "Sin geografías listadas.",
        "ngo_summary.privacy_footer": "Datos agregados solamente · las aplicaciones individuales y montos nunca aparecen aquí · publicado por la ONG.",
        "ngo_summary.not_published_title": "Esta ONG no ha optado por un resumen público",
        "ngo_summary.not_published_hint": "La ONG puede elegir publicar un resumen desde su perfil organizacional.",
        "timeline.eyebrow": "Actividad de la solicitud",
        "timeline.title": "Todo lo que ha ocurrido",
        "timeline.event_count": "{n} evento(s)",
        "timeline.empty": "Sin actividad registrada. Los eventos aparecerán aquí conforme avance la solicitud.",
        "timeline.loading": "Cargando línea de tiempo…",
        "reviewer_briefing.eyebrow": "Briefing del revisor",
        "reviewer_briefing.title": "Qué sondear antes de calificar",
        "reviewer_briefing.subtitle": "La IA lee la solicitud + criterios y resalta las 3-5 preguntas más útiles. Ayuda a la consistencia del panel sin dictar veredictos.",
        "reviewer_briefing.computing": "Leyendo la solicitud…",
        "reviewer_briefing.probe_these": "Sondea esto en tu revisión",
        "reviewer_briefing.sparse": "La solicitud es muy escasa para un briefing útil. Espera a que la ONG complete más.",
        "reviewer_briefing.unavailable": "Briefing no disponible ahora. Puedes calificar manualmente.",
        "message_thread.eyebrow": "Conversación",
        "message_thread.title": "Hilo donante ↔ ONG",
        "message_thread.loading": "Cargando conversación…",
        "message_thread.empty": "Aún sin mensajes. Inicia la conversación abajo — ambos lados verán este hilo.",
        "message_thread.placeholder": "Haz una pregunta, comparte una aclaración o publica una actualización rápida… (máx 4,000 caracteres)",
        "message_thread.send_hint": "Ctrl/Cmd + Enter para enviar. Menciona con @usuario.",
        "message_thread.post": "Publicar",
        "calibration.eyebrow": "Calibración del panel",
        "calibration.status.tight": "Panel ajustado",
        "calibration.status.tight_hint": "Los revisores coinciden dentro de 8 puntos.",
        "calibration.status.normal": "Variación normal",
        "calibration.status.normal_hint": "Revisores dentro de 20 puntos — típico de revisión humana.",
        "calibration.status.divergent": "Panel divergente",
        "calibration.status.divergent_hint": "Brecha > 20 puntos — considera una revisión desempate.",
        "calibration.action_needed": "Acción recomendada: el panel diverge por más de 20 puntos. Pide rationale al/los revisor(es) atípicos o asigna un tercer revisor.",
        "broadcast.title": "Difundir a los aplicantes",
        "broadcast.description": "Envía un mensaje a cada ONG con una aplicación en esta subvención. Reciben por sus canales preferidos.",
        "broadcast.subject_label": "Asunto",
        "broadcast.subject_placeholder": "ej.: Fecha límite extendida 5 días",
        "broadcast.body_label": "Mensaje",
        "broadcast.body_placeholder": "Texto plano. Sé explícito — los destinatarios no verán adjuntos.",
        "broadcast.audience_label": "Audiencia",
        "broadcast.audience.all": "Todos los aplicantes",
        "broadcast.audience.drafts": "Solo borradores",
        "broadcast.audience.submitted": "Solo enviadas",
        "broadcast.send_button": "Enviar difusión",
        "broadcast.sent_title": "Difusión enviada.",
        "score_breakdown.eyebrow": "Desglose del puntaje",
        "score_breakdown.title": "Cómo se construye tu puntaje general",
        "score_breakdown.strongest": "Más fuerte",
        "score_breakdown.weakest": "Más débil",
        "score_breakdown.not_scored": "sin calificar",
        "score_breakdown.weight_label": "Peso {n}%",
    },

    # ----- Somali
    "so": {
        "trust_gap.eyebrow": "Xidh farqiga",
        "trust_gap.title": "Sida loo kor u qaado natiijada kalsoonida",
        "trust_gap.subtitle": "AI ayaa akhrida labada tiir + qaybaha hoose oo si mudnaan ah u qiimeeya tallaabooyinka saamaynta ugu badan.",
        "trust_gap.projection": "Saadaal",
        "trust_gap.try_next": "Isku day inta xigta",
        "trust_gap.computing": "Waxaa la xisaabinayaa falanqaynta…",
        "trust_gap.effort.low": "Dadaal yar",
        "trust_gap.effort.medium": "Dadaal dhexdhexaad ah",
        "trust_gap.effort.high": "Dadaal sare",
        "trust_gap.disclaimer": "Qiyamadu waa saadaal AI, ma aha damaanad. Bilow guulaha degdegga ah.",
        "donor_profile.back": "Ku noqo ururada",
        "donor_profile.portfolio_snapshot": "Muuqaalka portfolio",
        "donor_profile.open_grants": "Deeqaha furan",
        "donor_profile.committed": "La balanqaaday",
        "donor_profile.decision_speed": "Xawaaraha go'aanka",
        "donor_profile.decline_rate": "Heerka diidmada",
        "donor_profile.active_sectors": "Qaybaha firfircoon",
        "donor_profile.active_countries": "Dalalka firfircoon",
        "donor_profile.reporting_burden": "Culayska warbixinta",
        "donor_profile.see_grants": "Eeg deeqaha",
        "donor_profile.no_sectors": "Wali ma jiraan qaybo lagu xiray deeqaha.",
        "donor_profile.no_countries": "Wali ma jiraan dalal lagu xiray deeqaha.",
        "donor_profile.sparse_explainer": "Deeq-bixiyahan wuxuu leeyahay wax ka yar 3 codsi go'aamiyey — muunad aad u yar in la sifeeyo go'aanadiisa.",
        "ngo_summary.trust_at_glance": "Kalsoonida muuqaalka",
        "ngo_summary.delivery_snapshot": "Muuqaalka gudbinta",
        "ngo_summary.awarded": "La siiyay",
        "ngo_summary.active": "Firfircoon",
        "ngo_summary.reports": "Warbixinno",
        "ngo_summary.sectors": "Qaybaha",
        "ngo_summary.geographic_footprint": "Raadka juquraafi",
        "ngo_summary.no_sectors": "Lama qornin qaybo.",
        "ngo_summary.no_geographies": "Lama qornin juquraafiyooyin.",
        "ngo_summary.privacy_footer": "Xog wadareed kaliya · codsiyada gaarka ah iyo qadarka deeqaha weligood ma ka muuqdaan halkan · waxaa daabacay NGO-da laftiisa.",
        "ngo_summary.not_published_title": "NGO-dani ma dooran daabicidda muuqaal guud",
        "ngo_summary.not_published_hint": "NGO-du way dooran kartaa daabicidda muuqaal ka socda profile-keeda ururka.",
        "timeline.eyebrow": "Hawlaha codsiga",
        "timeline.title": "Wax kasta oo dhacay",
        "timeline.event_count": "{n} dhacdo",
        "timeline.empty": "Hawl lama diiwaangelin weli. Dhacdooyinku waxay ka muuqan doonaan halkan markay codsigu socdo.",
        "timeline.loading": "Soo dejinta xilliga…",
        "reviewer_briefing.eyebrow": "Warbixin dib-u-eegeyaha",
        "reviewer_briefing.title": "Waxa la baadho ka hor calaamadaynta",
        "reviewer_briefing.subtitle": "AI ayaa akhrida codsiga + shuruudaha waxayna soo bandhigtaa 3-5 su'aalood oo ugu muhiimsan. Waxay caawisaa joogteynta guddiga.",
        "reviewer_briefing.computing": "Waxaa la akhrinayaa codsiga…",
        "reviewer_briefing.probe_these": "Baadh kuwan dib-u-eegistaada",
        "reviewer_briefing.sparse": "Codsiga aad ayuu u dheecuusan tahay si loo abuuro warbixin faa'iido leh. Sug NGO-du intay sii buuxin lahayd.",
        "reviewer_briefing.unavailable": "Warbixinta ma jirto hadda. Wali waad calaamadeysan kartaa gacanta.",
        "message_thread.eyebrow": "Sheekaysi",
        "message_thread.title": "Xirir deeq-bixiye iyo NGO",
        "message_thread.loading": "Soo dejinta sheekaysiga…",
        "message_thread.empty": "Wali ma jiraan farriimo. Bilow sheekaysiga hoosta — labada dhinacba way arki doonaan xiririkan.",
        "message_thread.placeholder": "Weydiiso su'aal, wadaag caddayn ama dhig cusboonaysiin degdeg ah… (ugu badnaan 4,000 xaraf)",
        "message_thread.send_hint": "Ctrl/Cmd + Enter si aad u dirto. U xus iyada oo la adeegsanayo @username.",
        "message_thread.post": "Dir",
        "calibration.eyebrow": "Isku-dheelitirka guddiga",
        "calibration.status.tight": "Guddi adag",
        "calibration.status.tight_hint": "Dib-u-eegeyaashu way ku heshiiyaan 8 dhibcood gudahooda.",
        "calibration.status.normal": "Kala duwanaansho caadi ah",
        "calibration.status.normal_hint": "Dib-u-eegeyaal 20 dhibcood gudahooda — caadi ah dib-u-eegis bani-aadan.",
        "calibration.status.divergent": "Guddi kala duwan",
        "calibration.status.divergent_hint": "Kala bax > 20 dhibcood — fikir dib-u-eegis ku kala saara.",
        "calibration.action_needed": "Tallaabo waa lagu talinayaa: guddigu way kala duwan yihiin in ka badan 20 dhibcood. Weydii sababta dib-u-eegeyaasha kala duwan ama u qoondee dib-u-eegis saddexaad.",
        "broadcast.title": "U faafin codsadayaasha",
        "broadcast.description": "U dir hal farriin NGO walba oo codsi ku leh deeqdan. Qaataha wuxuu helaa kanaaladda uu jecel yahay.",
        "broadcast.subject_label": "Mawduuc",
        "broadcast.subject_placeholder": "tusaale: Tariikhda kama dambaysta ah waxaa lagu kordhiyay 5 maalmood",
        "broadcast.body_label": "Farriin",
        "broadcast.body_placeholder": "Qoraal sax ah. Cad noqo — qaataha ma arki doono lifaaqyada.",
        "broadcast.audience_label": "Dhageystayaal",
        "broadcast.audience.all": "Codsadayaasha oo dhan",
        "broadcast.audience.drafts": "Qabyo-qoraallada kaliya",
        "broadcast.audience.submitted": "Kuwa la gudbiyay kaliya",
        "broadcast.send_button": "Dir baahinta",
        "broadcast.sent_title": "Baahinta waa la diray.",
        "score_breakdown.eyebrow": "Burburka calaamada",
        "score_breakdown.title": "Sida calaamadaada guud loo dhisay",
        "score_breakdown.strongest": "Kii ugu xoogga badan",
        "score_breakdown.weakest": "Kii ugu daciifsan",
        "score_breakdown.not_scored": "lama calaamadayn",
        "score_breakdown.weight_label": "Miisaanka {n}%",
    },
}


def main():
    for locale, keys in KEYS.items():
        path = ROOT / f"{locale}.json"
        if not path.exists():
            print(f"  [skip] {locale}.json not found")
            continue
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        added = []
        updated = []
        for k, v in keys.items():
            if k not in data:
                added.append(k)
            elif data[k] != v:
                updated.append(k)
            data[k] = v
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
            f.write("\n")
        print(f"  {locale}.json: +{len(added)} new, ~{len(updated)} updated")


if __name__ == "__main__":
    main()
