"""One-shot helper: append the new grant.wizard.* keys to ar/fr/es/sw/so.

Run from repo root: py -3 frontend/scripts/add-wizard-keys.py
The keys are inserted right after grant.wizard.title_required to keep them
grouped. Idempotent — skips any key that already exists.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

NEW_KEYS = {
    "ar": {
        "grant.wizard.ai_analyzing": "يقوم الذكاء الاصطناعي بتحليل المستند…",
        "grant.wizard.ai_extracting": "يستخرج المتطلبات ومؤشرات الأداء وجداول التقارير",
        "grant.wizard.doc_analyzed": "تم تحليل المستند بنجاح",
        "grant.wizard.stat_requirements": "متطلبات",
        "grant.wizard.stat_sections": "أقسام",
        "grant.wizard.stat_indicators": "مؤشرات",
        "grant.wizard.reporting_requirements": "متطلبات التقارير",
        "grant.wizard.kpis": "مؤشرات الأداء الرئيسية",
        "grant.wizard.more_count": "+{n} أخرى",
        "grant.wizard.basics_prefilled": "تم تعبئة الحقول أدناه من المستند الذي رفعته. راجِعها وعدِّلها حسب الحاجة.",
        "grant.wizard.eligibility_intro": "فعِّل فئات الأهلية التي تريد أن يستوفيها المتقدمون. أضف التفاصيل واضبط الأوزان النسبية.",
        "grant.wizard.eligibility_prefilled": "تم تعبئة بعض المتطلبات من المستند الذي رفعته.",
        "grant.wizard.weight_label": "الوزن:",
        "grant.wizard.eligibility_details_placeholder": "صف المتطلبات المحددة…",
        "grant.wizard.custom_requirement": "متطلب مخصص",
        "grant.wizard.add_custom_requirement": "أضف متطلبًا مخصصًا",
        "grant.wizard.ai_design_guidance": "إرشادات التصميم بالذكاء الاصطناعي",
        "grant.wizard.suggested_exclusions": "استثناءات مقترحة",
        "grant.wizard.evaluation_intro": "حدد المعايير التي سيستخدمها المراجعون لتقييم الطلبات.",
        "grant.wizard.weight_total": "الإجمالي: {n}%",
        "grant.wizard.weight_must_total": " (يجب أن يساوي 100%)",
        "grant.wizard.designing": "جارٍ التصميم…",
        "grant.wizard.design_with_ai": "صمِّم بالذكاء الاصطناعي",
        "grant.wizard.add": "أضف",
        "grant.wizard.criterion_n": "المعيار {n}",
        "grant.wizard.remove_criterion": "احذف المعيار",
        "grant.wizard.label_required": "التسمية *",
        "grant.wizard.label_placeholder": "مثلاً: المنهج التقني",
        "grant.wizard.weight_pct": "الوزن %",
        "grant.wizard.description_placeholder": "ما الذي يجب أن يتناوله المتقدمون…",
        "grant.wizard.instructions": "تعليمات للمتقدمين",
        "grant.wizard.instructions_placeholder": "إرشادات حول كيفية الإجابة…",
        "grant.wizard.max_words": "الحد الأقصى للكلمات",
        "grant.wizard.docs_intro": "اختر المستندات التي يجب على المتقدمين رفعها. انقر على البطاقة لتفعيلها ثم أضف المتطلبات الخاصة.",
        "grant.wizard.doc_specific_placeholder": "متطلبات محددة لهذا المستند…",
        "grant.wizard.doc_required_label": "إلزامي (يجب على المتقدم رفعه)",
        "grant.wizard.review_intro": "راجع منحتك قبل النشر",
        "grant.wizard.required_fields_missing": "حقول مطلوبة ناقصة:",
        "grant.wizard.missing.title": "العنوان",
        "grant.wizard.missing.funding": "مبلغ التمويل",
        "grant.wizard.missing.deadline": "الموعد النهائي",
        "grant.wizard.go_back_to_basics": "ارجع إلى <b>المعلومات الأساسية</b> (الخطوة 2) لإكمالها قبل النشر.",
        "grant.wizard.ai_extracted_data": "البيانات المستخرجة بالذكاء الاصطناعي",
        "grant.wizard.reporting_requirements_count": "متطلبات التقارير ({n})",
        "grant.wizard.kpis_count": "مؤشرات الأداء ({n})",
        "grant.wizard.kpi_target": " — الهدف: {target}",
        "grant.wizard.ready_to_publish": "جاهزة للنشر؟",
        "grant.wizard.publish_subtitle": "ستكون منحتك ظاهرة فورًا للمنظمات غير الحكومية المطابقة",
        "grant.wizard.saving_dots": "جارٍ الحفظ…",
        "grant.wizard.save_draft": "احفظ المسودة",
        "grant.wizard.publishing": "جارٍ النشر…",
        "grant.wizard.publish_grant": "انشر المنحة",
        "grant.wizard.requirement_fallback": "متطلب",
        "grant.wizard.indicator_fallback": "مؤشر",
        "grant.wizard.kpi_fallback": "مؤشر أداء",
    },
    "fr": {
        "grant.wizard.ai_analyzing": "L'IA analyse votre document…",
        "grant.wizard.ai_extracting": "Extraction des exigences, KPI et calendriers de rapport",
        "grant.wizard.doc_analyzed": "Document analysé avec succès",
        "grant.wizard.stat_requirements": "Exigences",
        "grant.wizard.stat_sections": "Sections",
        "grant.wizard.stat_indicators": "Indicateurs",
        "grant.wizard.reporting_requirements": "Exigences de rapport",
        "grant.wizard.kpis": "Indicateurs clés de performance",
        "grant.wizard.more_count": "+{n} de plus",
        "grant.wizard.basics_prefilled": "Les champs ci-dessous ont été pré-remplis depuis votre document. Vérifiez et ajustez si nécessaire.",
        "grant.wizard.eligibility_intro": "Activez les catégories d'éligibilité que les candidats doivent satisfaire. Ajoutez des détails et définissez les poids relatifs.",
        "grant.wizard.eligibility_prefilled": "Certaines exigences ont été pré-remplies depuis votre document.",
        "grant.wizard.weight_label": "Poids :",
        "grant.wizard.eligibility_details_placeholder": "Décrivez les exigences spécifiques…",
        "grant.wizard.custom_requirement": "Exigence personnalisée",
        "grant.wizard.add_custom_requirement": "Ajouter une exigence personnalisée",
        "grant.wizard.ai_design_guidance": "Conseils de conception par IA",
        "grant.wizard.suggested_exclusions": "Exclusions suggérées",
        "grant.wizard.evaluation_intro": "Définissez les critères que les évaluateurs utiliseront pour évaluer les candidatures.",
        "grant.wizard.weight_total": "Total : {n}%",
        "grant.wizard.weight_must_total": " (doit être 100%)",
        "grant.wizard.designing": "Conception en cours…",
        "grant.wizard.design_with_ai": "Concevoir avec l'IA",
        "grant.wizard.add": "Ajouter",
        "grant.wizard.criterion_n": "Critère {n}",
        "grant.wizard.remove_criterion": "Supprimer le critère",
        "grant.wizard.label_required": "Libellé *",
        "grant.wizard.label_placeholder": "ex. : Approche technique",
        "grant.wizard.weight_pct": "Poids %",
        "grant.wizard.description_placeholder": "Ce que les candidats doivent aborder…",
        "grant.wizard.instructions": "Instructions pour les candidats",
        "grant.wizard.instructions_placeholder": "Conseils sur comment répondre…",
        "grant.wizard.max_words": "Mots max",
        "grant.wizard.docs_intro": "Sélectionnez les documents que les candidats doivent téléverser. Cliquez sur une carte pour l'activer, puis ajoutez les exigences spécifiques.",
        "grant.wizard.doc_specific_placeholder": "Exigences spécifiques pour ce document…",
        "grant.wizard.doc_required_label": "Requis (le candidat doit téléverser)",
        "grant.wizard.review_intro": "Vérifiez votre subvention avant publication",
        "grant.wizard.required_fields_missing": "Champs requis manquants :",
        "grant.wizard.missing.title": "Titre",
        "grant.wizard.missing.funding": "Montant du financement",
        "grant.wizard.missing.deadline": "Date limite",
        "grant.wizard.go_back_to_basics": "Retournez à <b>Informations de base</b> (Étape 2) pour les compléter avant publication.",
        "grant.wizard.ai_extracted_data": "Données extraites par IA",
        "grant.wizard.reporting_requirements_count": "Exigences de rapport ({n})",
        "grant.wizard.kpis_count": "KPI / Indicateurs ({n})",
        "grant.wizard.kpi_target": " — Cible : {target}",
        "grant.wizard.ready_to_publish": "Prêt à publier ?",
        "grant.wizard.publish_subtitle": "Votre subvention sera immédiatement visible aux ONG correspondantes",
        "grant.wizard.saving_dots": "Enregistrement…",
        "grant.wizard.save_draft": "Enregistrer brouillon",
        "grant.wizard.publishing": "Publication…",
        "grant.wizard.publish_grant": "Publier la subvention",
        "grant.wizard.requirement_fallback": "Exigence",
        "grant.wizard.indicator_fallback": "Indicateur",
        "grant.wizard.kpi_fallback": "KPI",
    },
    "es": {
        "grant.wizard.ai_analyzing": "La IA está analizando tu documento…",
        "grant.wizard.ai_extracting": "Extrayendo requisitos, KPI y cronogramas de reportes",
        "grant.wizard.doc_analyzed": "Documento analizado exitosamente",
        "grant.wizard.stat_requirements": "Requisitos",
        "grant.wizard.stat_sections": "Secciones",
        "grant.wizard.stat_indicators": "Indicadores",
        "grant.wizard.reporting_requirements": "Requisitos de reporte",
        "grant.wizard.kpis": "Indicadores clave de desempeño",
        "grant.wizard.more_count": "+{n} más",
        "grant.wizard.basics_prefilled": "Los campos a continuación se han pre-rellenado con tu documento. Revisa y ajusta según sea necesario.",
        "grant.wizard.eligibility_intro": "Activa las categorías de elegibilidad que los postulantes deben cumplir. Agrega detalles y establece pesos relativos.",
        "grant.wizard.eligibility_prefilled": "Algunos requisitos se han pre-rellenado desde tu documento.",
        "grant.wizard.weight_label": "Peso:",
        "grant.wizard.eligibility_details_placeholder": "Describe requisitos específicos…",
        "grant.wizard.custom_requirement": "Requisito personalizado",
        "grant.wizard.add_custom_requirement": "Agregar requisito personalizado",
        "grant.wizard.ai_design_guidance": "Guía de diseño por IA",
        "grant.wizard.suggested_exclusions": "Exclusiones sugeridas",
        "grant.wizard.evaluation_intro": "Define los criterios que los evaluadores usarán para evaluar las postulaciones.",
        "grant.wizard.weight_total": "Total: {n}%",
        "grant.wizard.weight_must_total": " (debe ser 100%)",
        "grant.wizard.designing": "Diseñando…",
        "grant.wizard.design_with_ai": "Diseñar con IA",
        "grant.wizard.add": "Agregar",
        "grant.wizard.criterion_n": "Criterio {n}",
        "grant.wizard.remove_criterion": "Eliminar criterio",
        "grant.wizard.label_required": "Etiqueta *",
        "grant.wizard.label_placeholder": "ej.: Enfoque técnico",
        "grant.wizard.weight_pct": "Peso %",
        "grant.wizard.description_placeholder": "Qué deben abordar los postulantes…",
        "grant.wizard.instructions": "Instrucciones para postulantes",
        "grant.wizard.instructions_placeholder": "Guía sobre cómo responder…",
        "grant.wizard.max_words": "Palabras máx.",
        "grant.wizard.docs_intro": "Selecciona qué documentos deben subir los postulantes. Haz clic en una tarjeta para activarla, luego agrega requisitos específicos.",
        "grant.wizard.doc_specific_placeholder": "Requisitos específicos para este documento…",
        "grant.wizard.doc_required_label": "Requerido (el postulante debe subir)",
        "grant.wizard.review_intro": "Revisa tu subvención antes de publicar",
        "grant.wizard.required_fields_missing": "Campos requeridos faltantes:",
        "grant.wizard.missing.title": "Título",
        "grant.wizard.missing.funding": "Monto del financiamiento",
        "grant.wizard.missing.deadline": "Fecha límite",
        "grant.wizard.go_back_to_basics": "Vuelve a <b>Información básica</b> (Paso 2) para completarlos antes de publicar.",
        "grant.wizard.ai_extracted_data": "Datos extraídos por IA",
        "grant.wizard.reporting_requirements_count": "Requisitos de reporte ({n})",
        "grant.wizard.kpis_count": "KPI / Indicadores ({n})",
        "grant.wizard.kpi_target": " — Meta: {target}",
        "grant.wizard.ready_to_publish": "¿Listo para publicar?",
        "grant.wizard.publish_subtitle": "Tu subvención será visible inmediatamente a las ONG coincidentes",
        "grant.wizard.saving_dots": "Guardando…",
        "grant.wizard.save_draft": "Guardar borrador",
        "grant.wizard.publishing": "Publicando…",
        "grant.wizard.publish_grant": "Publicar subvención",
        "grant.wizard.requirement_fallback": "Requisito",
        "grant.wizard.indicator_fallback": "Indicador",
        "grant.wizard.kpi_fallback": "KPI",
    },
    "sw": {
        "grant.wizard.ai_analyzing": "AI inachambua hati yako…",
        "grant.wizard.ai_extracting": "Inatoa sharti, KPI, na ratiba za ripoti",
        "grant.wizard.doc_analyzed": "Hati imechambuliwa kwa mafanikio",
        "grant.wizard.stat_requirements": "Sharti",
        "grant.wizard.stat_sections": "Sehemu",
        "grant.wizard.stat_indicators": "Viashiria",
        "grant.wizard.reporting_requirements": "Sharti za ripoti",
        "grant.wizard.kpis": "Viashiria muhimu vya utendaji",
        "grant.wizard.more_count": "+{n} zaidi",
        "grant.wizard.basics_prefilled": "Mashamba yaliyo hapa chini yamejazwa kutoka kwa hati uliyopakia. Kagua na urekebishe kama inavyohitajika.",
        "grant.wizard.eligibility_intro": "Geuza vifungu vya ustahiki ambavyo ungetaka waombaji watimize. Ongeza maelezo na weka uzito wa jamaa.",
        "grant.wizard.eligibility_prefilled": "Baadhi ya sharti zimejazwa kutoka kwa hati uliyopakia.",
        "grant.wizard.weight_label": "Uzito:",
        "grant.wizard.eligibility_details_placeholder": "Eleza sharti maalum…",
        "grant.wizard.custom_requirement": "Sharti maalum",
        "grant.wizard.add_custom_requirement": "Ongeza sharti maalum",
        "grant.wizard.ai_design_guidance": "Mwongozo wa muundo wa AI",
        "grant.wizard.suggested_exclusions": "Vighairi vilivyopendekezwa",
        "grant.wizard.evaluation_intro": "Fafanua vigezo ambavyo wakaguzi watatumia kutathmini maombi.",
        "grant.wizard.weight_total": "Jumla: {n}%",
        "grant.wizard.weight_must_total": " (lazima iwe 100%)",
        "grant.wizard.designing": "Inabuni…",
        "grant.wizard.design_with_ai": "Buni na AI",
        "grant.wizard.add": "Ongeza",
        "grant.wizard.criterion_n": "Kigezo cha {n}",
        "grant.wizard.remove_criterion": "Ondoa kigezo",
        "grant.wizard.label_required": "Lebo *",
        "grant.wizard.label_placeholder": "k.m.: Mbinu ya kiufundi",
        "grant.wizard.weight_pct": "Uzito %",
        "grant.wizard.description_placeholder": "Ni nini waombaji wanapaswa kujadili…",
        "grant.wizard.instructions": "Maagizo kwa waombaji",
        "grant.wizard.instructions_placeholder": "Mwongozo kuhusu jinsi ya kujibu…",
        "grant.wizard.max_words": "Maneno ya juu",
        "grant.wizard.docs_intro": "Chagua hati ambazo waombaji lazima wapakie. Bofya kadi kuianzisha, kisha ongeza sharti maalum.",
        "grant.wizard.doc_specific_placeholder": "Sharti maalum kwa hati hii…",
        "grant.wizard.doc_required_label": "Inahitajika (mwombaji lazima apakie)",
        "grant.wizard.review_intro": "Kagua ruzuku yako kabla ya kuchapisha",
        "grant.wizard.required_fields_missing": "Mashamba yanayohitajika yamekosa:",
        "grant.wizard.missing.title": "Kichwa",
        "grant.wizard.missing.funding": "Kiasi cha ufadhili",
        "grant.wizard.missing.deadline": "Tarehe ya mwisho",
        "grant.wizard.go_back_to_basics": "Rudi kwenye <b>Maelezo ya msingi</b> (Hatua 2) ili kuyakamilisha kabla ya kuchapisha.",
        "grant.wizard.ai_extracted_data": "Data iliyotolewa na AI",
        "grant.wizard.reporting_requirements_count": "Sharti za ripoti ({n})",
        "grant.wizard.kpis_count": "KPI / Viashiria ({n})",
        "grant.wizard.kpi_target": " — Lengo: {target}",
        "grant.wizard.ready_to_publish": "Tayari kuchapisha?",
        "grant.wizard.publish_subtitle": "Ruzuku yako itaonekana mara moja kwa NGO zinazolingana",
        "grant.wizard.saving_dots": "Inahifadhi…",
        "grant.wizard.save_draft": "Hifadhi rasimu",
        "grant.wizard.publishing": "Inachapisha…",
        "grant.wizard.publish_grant": "Chapisha ruzuku",
        "grant.wizard.requirement_fallback": "Sharti",
        "grant.wizard.indicator_fallback": "Kiashiria",
        "grant.wizard.kpi_fallback": "KPI",
    },
    "so": {
        "grant.wizard.ai_analyzing": "AI-gu wuxuu falanqaynayaa dukumeentigaaga…",
        "grant.wizard.ai_extracting": "Waxaa la soo saarayaa shuruudaha, KPI-yada, iyo jadwalka warbixinta",
        "grant.wizard.doc_analyzed": "Dukumeentiga si guul leh ayaa loo falanqeeyay",
        "grant.wizard.stat_requirements": "Shuruudo",
        "grant.wizard.stat_sections": "Qaybo",
        "grant.wizard.stat_indicators": "Tilmaamaha",
        "grant.wizard.reporting_requirements": "Shuruudaha warbixinta",
        "grant.wizard.kpis": "Tilmaamaha waxqabadka muhiimka ah",
        "grant.wizard.more_count": "+{n} kale",
        "grant.wizard.basics_prefilled": "Goobaha hoose waxaa horay loogu buuxiyay dukumeentigaagii. Dib u eeg oo hagaaji haddii loo baahdo.",
        "grant.wizard.eligibility_intro": "Daar qaybaha xaq u yeelashada aad rabto in codsadayaashu buuxiyaan. Ku dar faahfaahin oo dejiso miisaanka.",
        "grant.wizard.eligibility_prefilled": "Qaar ka mid ah shuruudaha waxaa horay loogu buuxiyay dukumeentigaagii.",
        "grant.wizard.weight_label": "Miisaan:",
        "grant.wizard.eligibility_details_placeholder": "Sharax shuruudaha gaarka ah…",
        "grant.wizard.custom_requirement": "Shuruud caadi ah",
        "grant.wizard.add_custom_requirement": "Ku dar shuruud caadi ah",
        "grant.wizard.ai_design_guidance": "Hagidda nakhshadda AI",
        "grant.wizard.suggested_exclusions": "Ka-saarista la soo jeediyay",
        "grant.wizard.evaluation_intro": "Sharax cabbirrada uu eegaa eegayaal isticmaali doonaan si ay u qiimeeyaan codsiyada.",
        "grant.wizard.weight_total": "Wadarta: {n}%",
        "grant.wizard.weight_must_total": " (waa inay tahay 100%)",
        "grant.wizard.designing": "Naqshadeyn…",
        "grant.wizard.design_with_ai": "Naqshadee adoo isticmaalaya AI",
        "grant.wizard.add": "Ku dar",
        "grant.wizard.criterion_n": "Cabbirka {n}",
        "grant.wizard.remove_criterion": "Ka saar cabbirka",
        "grant.wizard.label_required": "Calaamad *",
        "grant.wizard.label_placeholder": "tus.: Qaabka tikniyoolojiyada",
        "grant.wizard.weight_pct": "Miisaanka %",
        "grant.wizard.description_placeholder": "Waxa ay codsadayaashu khusayso inay ka hadlaan…",
        "grant.wizard.instructions": "Tilmaamaha codsadayaasha",
        "grant.wizard.instructions_placeholder": "Hagidda sida loo jawaabo…",
        "grant.wizard.max_words": "Erayada ugu badan",
        "grant.wizard.docs_intro": "Dooro dukumeentiyada ay codsadayaashu waa inay soo dejiyaan. Guji kaarka si aad u shidato, ka dibna ku dar shuruudaha gaarka ah.",
        "grant.wizard.doc_specific_placeholder": "Shuruudaha gaarka ah ee dukumeentigan…",
        "grant.wizard.doc_required_label": "Lagama maarmaan (codsaduhu waa inuu soo dejiyo)",
        "grant.wizard.review_intro": "Eeg deeqdaada ka hor inta aadan daabicin",
        "grant.wizard.required_fields_missing": "Goobaha loo baahan yahay way maqan yihiin:",
        "grant.wizard.missing.title": "Cinwaan",
        "grant.wizard.missing.funding": "Lacagta maalgelinta",
        "grant.wizard.missing.deadline": "Wakhtiga ugu dambeeya",
        "grant.wizard.go_back_to_basics": "Ku noqo <b>Macluumaadka aasaasiga</b> (Tallaabada 2) si aad u dhammaystirto ka hor daabacaadda.",
        "grant.wizard.ai_extracted_data": "Xogta laga soo saaray AI",
        "grant.wizard.reporting_requirements_count": "Shuruudaha warbixinta ({n})",
        "grant.wizard.kpis_count": "KPI / Tilmaamaha ({n})",
        "grant.wizard.kpi_target": " — Bartilmaameedka: {target}",
        "grant.wizard.ready_to_publish": "Diyaar u tahay daabacaad?",
        "grant.wizard.publish_subtitle": "Deeqdaada waxay isla markiiba u muuqan doontaa NGO-yada u dhigma",
        "grant.wizard.saving_dots": "Waxaa la kaydinayaa…",
        "grant.wizard.save_draft": "Kaydi qabyada",
        "grant.wizard.publishing": "Waxaa la daabacayaa…",
        "grant.wizard.publish_grant": "Daabac deeqda",
        "grant.wizard.requirement_fallback": "Shuruud",
        "grant.wizard.indicator_fallback": "Tilmaame",
        "grant.wizard.kpi_fallback": "KPI",
    },
}

# Sectors and countries — common taxonomy values displayed across the donor
# wizard, the apply form, and search filters. Keys map to the canonical
# English value (which stays the underlying DB value) → localized label.
TAXONOMY_KEYS = {
    "en": {
        "sector.health": "Health",
        "sector.education": "Education",
        "sector.wash": "WASH",
        "sector.climate": "Climate",
        "sector.protection": "Protection",
        "sector.nutrition": "Nutrition",
        "sector.livelihoods": "Livelihoods",
        "sector.governance": "Governance",
        "sector.agriculture": "Agriculture",
        "sector.gender_equality": "Gender Equality",
        "country.kenya": "Kenya",
        "country.somalia": "Somalia",
        "country.ethiopia": "Ethiopia",
        "country.uganda": "Uganda",
        "country.tanzania": "Tanzania",
        "country.south_sudan": "South Sudan",
        "country.nigeria": "Nigeria",
        "country.south_africa": "South Africa",
    },
    "ar": {
        "sector.health": "الصحة",
        "sector.education": "التعليم",
        "sector.wash": "المياه والصرف الصحي",
        "sector.climate": "المناخ",
        "sector.protection": "الحماية",
        "sector.nutrition": "التغذية",
        "sector.livelihoods": "سبل العيش",
        "sector.governance": "الحوكمة",
        "sector.agriculture": "الزراعة",
        "sector.gender_equality": "المساواة بين الجنسين",
        "country.kenya": "كينيا",
        "country.somalia": "الصومال",
        "country.ethiopia": "إثيوبيا",
        "country.uganda": "أوغندا",
        "country.tanzania": "تنزانيا",
        "country.south_sudan": "جنوب السودان",
        "country.nigeria": "نيجيريا",
        "country.south_africa": "جنوب أفريقيا",
    },
    "fr": {
        "sector.health": "Santé",
        "sector.education": "Éducation",
        "sector.wash": "EAH",
        "sector.climate": "Climat",
        "sector.protection": "Protection",
        "sector.nutrition": "Nutrition",
        "sector.livelihoods": "Moyens de subsistance",
        "sector.governance": "Gouvernance",
        "sector.agriculture": "Agriculture",
        "sector.gender_equality": "Égalité des genres",
        "country.kenya": "Kenya",
        "country.somalia": "Somalie",
        "country.ethiopia": "Éthiopie",
        "country.uganda": "Ouganda",
        "country.tanzania": "Tanzanie",
        "country.south_sudan": "Soudan du Sud",
        "country.nigeria": "Nigeria",
        "country.south_africa": "Afrique du Sud",
    },
    "es": {
        "sector.health": "Salud",
        "sector.education": "Educación",
        "sector.wash": "Agua y saneamiento",
        "sector.climate": "Clima",
        "sector.protection": "Protección",
        "sector.nutrition": "Nutrición",
        "sector.livelihoods": "Medios de vida",
        "sector.governance": "Gobernanza",
        "sector.agriculture": "Agricultura",
        "sector.gender_equality": "Igualdad de género",
        "country.kenya": "Kenia",
        "country.somalia": "Somalia",
        "country.ethiopia": "Etiopía",
        "country.uganda": "Uganda",
        "country.tanzania": "Tanzania",
        "country.south_sudan": "Sudán del Sur",
        "country.nigeria": "Nigeria",
        "country.south_africa": "Sudáfrica",
    },
    "sw": {
        "sector.health": "Afya",
        "sector.education": "Elimu",
        "sector.wash": "Maji na usafi",
        "sector.climate": "Hali ya hewa",
        "sector.protection": "Ulinzi",
        "sector.nutrition": "Lishe",
        "sector.livelihoods": "Maisha",
        "sector.governance": "Utawala",
        "sector.agriculture": "Kilimo",
        "sector.gender_equality": "Usawa wa kijinsia",
        "country.kenya": "Kenya",
        "country.somalia": "Somalia",
        "country.ethiopia": "Ethiopia",
        "country.uganda": "Uganda",
        "country.tanzania": "Tanzania",
        "country.south_sudan": "Sudan Kusini",
        "country.nigeria": "Nigeria",
        "country.south_africa": "Afrika Kusini",
    },
    "so": {
        "sector.health": "Caafimaad",
        "sector.education": "Waxbarasho",
        "sector.wash": "Biyo iyo nadaafad",
        "sector.climate": "Cimilada",
        "sector.protection": "Ilaalin",
        "sector.nutrition": "Nafaqo",
        "sector.livelihoods": "Nolol-maalmeed",
        "sector.governance": "Maamul",
        "sector.agriculture": "Beeraha",
        "sector.gender_equality": "Sinnaanta jinsiyada",
        "country.kenya": "Kenya",
        "country.somalia": "Soomaaliya",
        "country.ethiopia": "Itoobiya",
        "country.uganda": "Yugaanda",
        "country.tanzania": "Tanzaniya",
        "country.south_sudan": "Koonfurta Suudaan",
        "country.nigeria": "Nayjeeriya",
        "country.south_africa": "Koonfur Afrika",
    },
}


def merge_keys(lang: str, additions: dict) -> int:
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return added


def main():
    for lang, keys in NEW_KEYS.items():
        n = merge_keys(lang, keys)
        print(f"{lang}: +{n} wizard keys")
    for lang, keys in TAXONOMY_KEYS.items():
        n = merge_keys(lang, keys)
        print(f"{lang}: +{n} taxonomy keys")


if __name__ == "__main__":
    main()
