"""Phase 4.3 UI — i18n keys for the grant Q&A panel."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

KEYS = {
    "en": {
        "grant_qa.heading": "Questions about this grant",
        "grant_qa.heading_anchored": "Questions about: {anchor}",
        "grant_qa.ngo_subtitle": "Ask the donor a question. Once they answer, the answer becomes visible to every NGO applying.",
        "grant_qa.donor_subtitle": "Answers you give are visible to every NGO applying to this grant.",
        "grant_qa.loading": "Loading questions…",
        "grant_qa.empty": "No questions yet.",
        "grant_qa.status.pending": "Pending",
        "grant_qa.status.answered": "Answered",
        "grant_qa.status.moderated": "Hidden",
        "grant_qa.answer_label": "Donor's answer",
        "grant_qa.answer_placeholder": "Write your answer — it will be visible to every applicant.",
        "grant_qa.ask_label": "Your question",
        "grant_qa.ask_placeholder": "Ask the donor anything you'd like clarified before submitting.",
        "grant_qa.public_after_answer": "Becomes public once answered",
        "grant_qa.cta.ask": "Ask",
        "grant_qa.cta.answer": "Send answer",
        "grant_qa.cta.moderate": "Hide from public Q&A",
        "grant_qa.confirm_moderate": "Hide this question from the public Q&A? It will remain in the audit log.",
        "grant_qa.toast.asked": "Question sent to the donor",
        "grant_qa.toast.answered": "Answer published — visible to all applicants",
        "grant_qa.toast.moderated": "Question hidden from public Q&A",
    },
    "ar": {
        "grant_qa.heading": "أسئلة حول هذه المنحة",
        "grant_qa.heading_anchored": "أسئلة حول: {anchor}",
        "grant_qa.ngo_subtitle": "اطرح سؤالاً على المانح. بمجرد إجابته، يصبح الجواب مرئياً لكل المتقدمين لهذه المنحة.",
        "grant_qa.donor_subtitle": "الإجابات التي تقدّمها مرئية لكل منظمة تتقدّم لهذه المنحة.",
        "grant_qa.loading": "جارٍ تحميل الأسئلة…",
        "grant_qa.empty": "لا توجد أسئلة بعد.",
        "grant_qa.status.pending": "قيد الانتظار",
        "grant_qa.status.answered": "تمّت الإجابة",
        "grant_qa.status.moderated": "مخفي",
        "grant_qa.answer_label": "إجابة المانح",
        "grant_qa.answer_placeholder": "اكتب إجابتك — ستكون مرئية لكل المتقدمين.",
        "grant_qa.ask_label": "سؤالك",
        "grant_qa.ask_placeholder": "اسأل المانح عن أي شيء تريد توضيحه قبل التقديم.",
        "grant_qa.public_after_answer": "يصبح علنياً بعد الإجابة",
        "grant_qa.cta.ask": "اسأل",
        "grant_qa.cta.answer": "أرسل الإجابة",
        "grant_qa.cta.moderate": "إخفاء من الأسئلة العامة",
        "grant_qa.confirm_moderate": "هل تريد إخفاء هذا السؤال من الأسئلة العامة؟ سيبقى في سجل التدقيق.",
        "grant_qa.toast.asked": "تم إرسال السؤال إلى المانح",
        "grant_qa.toast.answered": "تم نشر الإجابة — مرئية لكل المتقدمين",
        "grant_qa.toast.moderated": "تم إخفاء السؤال من الأسئلة العامة",
    },
    "fr": {
        "grant_qa.heading": "Questions sur cette subvention",
        "grant_qa.heading_anchored": "Questions sur : {anchor}",
        "grant_qa.ngo_subtitle": "Posez une question au bailleur. Dès qu'il répond, la réponse devient visible pour toutes les ONG qui postulent.",
        "grant_qa.donor_subtitle": "Les réponses que vous donnez sont visibles par toutes les ONG postulant à cette subvention.",
        "grant_qa.loading": "Chargement des questions…",
        "grant_qa.empty": "Aucune question pour le moment.",
        "grant_qa.status.pending": "En attente",
        "grant_qa.status.answered": "Répondu",
        "grant_qa.status.moderated": "Masqué",
        "grant_qa.answer_label": "Réponse du bailleur",
        "grant_qa.answer_placeholder": "Écrivez votre réponse — elle sera visible par tous les candidats.",
        "grant_qa.ask_label": "Votre question",
        "grant_qa.ask_placeholder": "Demandez au bailleur tout point à clarifier avant de soumettre.",
        "grant_qa.public_after_answer": "Devient publique après réponse",
        "grant_qa.cta.ask": "Demander",
        "grant_qa.cta.answer": "Envoyer la réponse",
        "grant_qa.cta.moderate": "Masquer des Q&R publiques",
        "grant_qa.confirm_moderate": "Masquer cette question des Q&R publiques ? Elle restera dans le journal d'audit.",
        "grant_qa.toast.asked": "Question envoyée au bailleur",
        "grant_qa.toast.answered": "Réponse publiée — visible par tous les candidats",
        "grant_qa.toast.moderated": "Question masquée des Q&R publiques",
    },
    "es": {
        "grant_qa.heading": "Preguntas sobre esta subvención",
        "grant_qa.heading_anchored": "Preguntas sobre: {anchor}",
        "grant_qa.ngo_subtitle": "Haz una pregunta al donante. Una vez que responda, la respuesta será visible para todas las ONG que postulen.",
        "grant_qa.donor_subtitle": "Las respuestas que des serán visibles para todas las ONG que postulen a esta subvención.",
        "grant_qa.loading": "Cargando preguntas…",
        "grant_qa.empty": "Aún no hay preguntas.",
        "grant_qa.status.pending": "Pendiente",
        "grant_qa.status.answered": "Respondida",
        "grant_qa.status.moderated": "Oculta",
        "grant_qa.answer_label": "Respuesta del donante",
        "grant_qa.answer_placeholder": "Escribe tu respuesta — será visible para todos los postulantes.",
        "grant_qa.ask_label": "Tu pregunta",
        "grant_qa.ask_placeholder": "Pregunta al donante cualquier cosa que quieras aclarar antes de enviar.",
        "grant_qa.public_after_answer": "Se hace pública al responder",
        "grant_qa.cta.ask": "Preguntar",
        "grant_qa.cta.answer": "Enviar respuesta",
        "grant_qa.cta.moderate": "Ocultar del Q&A público",
        "grant_qa.confirm_moderate": "¿Ocultar esta pregunta del Q&A público? Permanecerá en el registro de auditoría.",
        "grant_qa.toast.asked": "Pregunta enviada al donante",
        "grant_qa.toast.answered": "Respuesta publicada — visible para todos los postulantes",
        "grant_qa.toast.moderated": "Pregunta ocultada del Q&A público",
    },
    "sw": {
        "grant_qa.heading": "Maswali kuhusu ruzuku hii",
        "grant_qa.heading_anchored": "Maswali kuhusu: {anchor}",
        "grant_qa.ngo_subtitle": "Mwulize mfadhili swali. Mara watakapojibu, jibu litaonekana kwa kila NGO inayoomba.",
        "grant_qa.donor_subtitle": "Majibu unayotoa yataonekana kwa kila NGO inayoomba ruzuku hii.",
        "grant_qa.loading": "Inapakia maswali…",
        "grant_qa.empty": "Hakuna maswali bado.",
        "grant_qa.status.pending": "Inasubiri",
        "grant_qa.status.answered": "Imejibiwa",
        "grant_qa.status.moderated": "Imefichwa",
        "grant_qa.answer_label": "Jibu la mfadhili",
        "grant_qa.answer_placeholder": "Andika jibu lako — litaonekana kwa kila mwombaji.",
        "grant_qa.ask_label": "Swali lako",
        "grant_qa.ask_placeholder": "Mwulize mfadhili kitu chochote unachotaka kuelewa kabla ya kuwasilisha.",
        "grant_qa.public_after_answer": "Linakuwa la umma baada ya kujibiwa",
        "grant_qa.cta.ask": "Uliza",
        "grant_qa.cta.answer": "Tuma jibu",
        "grant_qa.cta.moderate": "Ficha kutoka kwa Q&A ya umma",
        "grant_qa.confirm_moderate": "Je, kuficha swali hili kutoka kwa Q&A ya umma? Litabaki kwenye kumbukumbu ya ukaguzi.",
        "grant_qa.toast.asked": "Swali limetumwa kwa mfadhili",
        "grant_qa.toast.answered": "Jibu limechapishwa — linaonekana kwa waombaji wote",
        "grant_qa.toast.moderated": "Swali limefichwa kutoka kwa Q&A ya umma",
    },
    "so": {
        "grant_qa.heading": "Su'aalo ku saabsan deeqdan",
        "grant_qa.heading_anchored": "Su'aalo ku saabsan: {anchor}",
        "grant_qa.ngo_subtitle": "Su'aal weydii deeq-bixiyaha. Marka ay ka jawaabaan, jawaabtu waxay u muuqan doontaa NGO kasta oo codsanaysa.",
        "grant_qa.donor_subtitle": "Jawaabaha aad bixiso waxay u muuqan doonaan NGO kasta oo codsanaysa deeqdan.",
        "grant_qa.loading": "Waxaa la soo dejinayaa su'aalaha…",
        "grant_qa.empty": "Wali ma jiraan su'aalo.",
        "grant_qa.status.pending": "Sugaya",
        "grant_qa.status.answered": "La jawaabay",
        "grant_qa.status.moderated": "La qariyey",
        "grant_qa.answer_label": "Jawaabta deeq-bixiyaha",
        "grant_qa.answer_placeholder": "Qor jawaabtaada — waxay u muuqan doontaa codsadayaasha oo dhan.",
        "grant_qa.ask_label": "Su'aashaada",
        "grant_qa.ask_placeholder": "Weydii deeq-bixiyaha wax kasta oo aad rabto in la kuu caddeeyo ka hor inta aadan gudbin.",
        "grant_qa.public_after_answer": "Waxay noqonaysaa mid dadweyne marka la jawaabo",
        "grant_qa.cta.ask": "Weydii",
        "grant_qa.cta.answer": "Dir jawaabta",
        "grant_qa.cta.moderate": "Ka qari Q&A-da dadweynaha",
        "grant_qa.confirm_moderate": "Ka qari su'aashan Q&A-da dadweynaha? Waxay ku sii jiri doontaa diiwaanka hubinta.",
        "grant_qa.toast.asked": "Su'aasha waxaa loo diray deeq-bixiyaha",
        "grant_qa.toast.answered": "Jawaabta waa la daabacay — waxay u muuqataa codsadayaasha oo dhan",
        "grant_qa.toast.moderated": "Su'aashii waxaa laga qariyey Q&A-da dadweynaha",
    },
}

for lang, additions in KEYS.items():
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lang}: +{added}")
