"""Phase 2.3 — donor portfolio diagnostics keys."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "frontend" / "src" / "i18n"

KEYS = {
    "en": {
        "portfolio.heading": "Portfolio diagnostics",
        "portfolio.subtitle": "Cross-grant patterns to help you tighten criteria and read your applicant pool.",
        "portfolio.loading": "Loading portfolio data…",
        "portfolio.metric.grants": "Grants",
        "portfolio.metric.submissions": "Submissions",
        "portfolio.metric.awarded": "Awarded",
        "portfolio.metric.avg_ai_score": "Avg AI score",
        "portfolio.anomalies_label": "Things to look at ({n})",
        "portfolio.per_grant_label": "Per-grant rollup ({n})",
        "portfolio.col.grant": "Grant",
        "portfolio.col.submissions": "Subs.",
        "portfolio.col.awarded": "Awarded",
        "portfolio.col.avg_score": "Avg score",
        "portfolio.col.spread": "Spread",
        "portfolio.anomaly.low_interest": "Only {n} submission(s). Consider broader sectors, lighter eligibility, or longer deadline.",
        "portfolio.anomaly.low_discrimination": "Score spread of just {spread} pts across applicants — criteria aren't separating winners from the pool. Tighten the highest-weight criterion.",
        "portfolio.anomaly.criteria_too_easy": "Average AI score is {avg}% — criteria may be too easy. Add specificity to keep the bar high.",
        "portfolio.anomaly.high_decline": "{pct}% of applicants are being declined — eligibility may be too narrow or criteria misaligned.",
    },
    "ar": {
        "portfolio.heading": "تشخيصات المحفظة",
        "portfolio.subtitle": "أنماط عبر المنح تساعدك على إحكام المعايير وفهم مجموعة المتقدمين.",
        "portfolio.loading": "جارٍ تحميل بيانات المحفظة…",
        "portfolio.metric.grants": "المنح",
        "portfolio.metric.submissions": "الطلبات",
        "portfolio.metric.awarded": "الممنوحة",
        "portfolio.metric.avg_ai_score": "متوسط درجة الذكاء الاصطناعي",
        "portfolio.anomalies_label": "أمور تستحق الاهتمام ({n})",
        "portfolio.per_grant_label": "إجمالي لكل منحة ({n})",
        "portfolio.col.grant": "المنحة",
        "portfolio.col.submissions": "طلبات",
        "portfolio.col.awarded": "ممنوحة",
        "portfolio.col.avg_score": "متوسط الدرجة",
        "portfolio.col.spread": "الفارق",
        "portfolio.anomaly.low_interest": "فقط {n} طلب. فكّر في توسيع القطاعات أو تخفيف الأهلية أو تمديد الموعد النهائي.",
        "portfolio.anomaly.low_discrimination": "فارق الدرجات {spread} نقطة فقط بين المتقدمين — المعايير لا تميّز بين الفائزين. أحكم أعلى معيار وزناً.",
        "portfolio.anomaly.criteria_too_easy": "متوسط درجة الذكاء الاصطناعي {avg}% — المعايير قد تكون سهلة جداً. أضف مزيداً من التحديد.",
        "portfolio.anomaly.high_decline": "نسبة الرفض {pct}% — الأهلية قد تكون ضيّقة أو المعايير غير متّسقة.",
    },
    "fr": {
        "portfolio.heading": "Diagnostics du portefeuille",
        "portfolio.subtitle": "Tendances inter-subventions pour resserrer vos critères et lire votre pool de candidats.",
        "portfolio.loading": "Chargement du portefeuille…",
        "portfolio.metric.grants": "Subventions",
        "portfolio.metric.submissions": "Candidatures",
        "portfolio.metric.awarded": "Attribuées",
        "portfolio.metric.avg_ai_score": "Score IA moyen",
        "portfolio.anomalies_label": "À examiner ({n})",
        "portfolio.per_grant_label": "Par subvention ({n})",
        "portfolio.col.grant": "Subvention",
        "portfolio.col.submissions": "Cand.",
        "portfolio.col.awarded": "Attribuées",
        "portfolio.col.avg_score": "Score moy.",
        "portfolio.col.spread": "Écart",
        "portfolio.anomaly.low_interest": "Seulement {n} candidature(s). Élargissez les secteurs, allégez l'éligibilité ou prolongez la date limite.",
        "portfolio.anomaly.low_discrimination": "Écart de scores de {spread} pts seulement — les critères ne séparent pas les vainqueurs. Resserrez le critère au poids le plus élevé.",
        "portfolio.anomaly.criteria_too_easy": "Score IA moyen de {avg}% — critères probablement trop simples. Ajoutez de la spécificité.",
        "portfolio.anomaly.high_decline": "{pct}% de candidatures rejetées — éligibilité trop étroite ou critères désalignés.",
    },
    "es": {
        "portfolio.heading": "Diagnóstico de portafolio",
        "portfolio.subtitle": "Patrones entre subvenciones para ajustar criterios y leer tu pool de postulantes.",
        "portfolio.loading": "Cargando portafolio…",
        "portfolio.metric.grants": "Subvenciones",
        "portfolio.metric.submissions": "Postulaciones",
        "portfolio.metric.awarded": "Adjudicadas",
        "portfolio.metric.avg_ai_score": "Puntaje IA promedio",
        "portfolio.anomalies_label": "Por revisar ({n})",
        "portfolio.per_grant_label": "Por subvención ({n})",
        "portfolio.col.grant": "Subvención",
        "portfolio.col.submissions": "Post.",
        "portfolio.col.awarded": "Adj.",
        "portfolio.col.avg_score": "Pts. prom.",
        "portfolio.col.spread": "Brecha",
        "portfolio.anomaly.low_interest": "Solo {n} postulación(es). Considera ampliar sectores, relajar elegibilidad o extender la fecha.",
        "portfolio.anomaly.low_discrimination": "Brecha de puntajes de solo {spread} pts — los criterios no separan ganadores. Ajusta el criterio de mayor peso.",
        "portfolio.anomaly.criteria_too_easy": "Puntaje IA promedio de {avg}% — los criterios pueden ser muy fáciles. Agrega especificidad.",
        "portfolio.anomaly.high_decline": "{pct}% de postulaciones rechazadas — elegibilidad muy estrecha o criterios desalineados.",
    },
    "sw": {
        "portfolio.heading": "Uchanganuzi wa kifurushi",
        "portfolio.subtitle": "Mitindo katika ruzuku zako kukusaidia kuimarisha vigezo na kuelewa kundi la waombaji.",
        "portfolio.loading": "Inapakia data ya kifurushi…",
        "portfolio.metric.grants": "Ruzuku",
        "portfolio.metric.submissions": "Maombi",
        "portfolio.metric.awarded": "Yaliyotolewa",
        "portfolio.metric.avg_ai_score": "Wastani wa alama za AI",
        "portfolio.anomalies_label": "Mambo ya kuangalia ({n})",
        "portfolio.per_grant_label": "Kwa kila ruzuku ({n})",
        "portfolio.col.grant": "Ruzuku",
        "portfolio.col.submissions": "Maombi",
        "portfolio.col.awarded": "Imetolewa",
        "portfolio.col.avg_score": "Wastani",
        "portfolio.col.spread": "Tofauti",
        "portfolio.anomaly.low_interest": "Maombi {n} pekee. Fikiria kupanua sekta, kupunguza ustahiki, au kupanua tarehe ya mwisho.",
        "portfolio.anomaly.low_discrimination": "Tofauti ya alama ni pointi {spread} tu kati ya waombaji — vigezo haviwagawanyi. Imarisha kigezo chenye uzito mkubwa zaidi.",
        "portfolio.anomaly.criteria_too_easy": "Wastani wa alama za AI ni {avg}% — vigezo huenda ni vya rahisi sana. Ongeza umakini.",
        "portfolio.anomaly.high_decline": "{pct}% ya maombi yanakataliwa — ustahiki unaweza kuwa mwembamba au vigezo havilingani.",
    },
    "so": {
        "portfolio.heading": "Baaritaanno xafaayadda",
        "portfolio.subtitle": "Hannaanno deeqdo dhexdood si aad cabbirrada u sii xoojiso oo aad u akhriddo kooxda codsadayaasha.",
        "portfolio.loading": "Waxaa la soo dejinayaa xogta xafaayadda…",
        "portfolio.metric.grants": "Deeqo",
        "portfolio.metric.submissions": "Codsiyo",
        "portfolio.metric.awarded": "La siiyay",
        "portfolio.metric.avg_ai_score": "Buundada AI ee celcelis",
        "portfolio.anomalies_label": "Waxyaabo eeg ({n})",
        "portfolio.per_grant_label": "Deeqdiiba ({n})",
        "portfolio.col.grant": "Deeqda",
        "portfolio.col.submissions": "Codsi.",
        "portfolio.col.awarded": "La siiyay",
        "portfolio.col.avg_score": "Celcelis",
        "portfolio.col.spread": "Kala-baxsanaan",
        "portfolio.anomaly.low_interest": "{n} codsi oo keliya. Tixgeli kororsiga qaybaha, fudaynta xaq u yeelashada, ama kordhinta wakhtiga ugu dambeeya.",
        "portfolio.anomaly.low_discrimination": "Kala-baxsanaanta buundooyinka waa dhibco {spread} oo keliya — cabbirrada ma kala saarayaan guuleystayaasha. Sii xoog cabbirka ugu miisaan badan.",
        "portfolio.anomaly.criteria_too_easy": "Buundada AI ee celcelis waa {avg}% — cabbirradu waxay yihiin kuwo aad u fudud. Ku dar gaarsii sax ah.",
        "portfolio.anomaly.high_decline": "{pct}% codsiyada waa la diidayaa — xaq u yeelashadu way ciriiri tahay ama cabbirradu way isku xidhanyihiin.",
    },
}

for lang, additions in KEYS.items():
    p = ROOT / f"{lang}.json"
    data = json.loads(p.read_text(encoding="utf-8"))
    added = 0
    for k, v in additions.items():
        if k not in data:
            data[k] = v
            added += 1
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lang}: +{added}")
