"""v3 integrity: updated_at on all models, unique constraint, numeric funding

Revision ID: 30f23f47c1c7
Revises: c4c076a04aeb
Create Date: 2026-03-04 11:29:48.902903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f23f47c1c7'
down_revision = 'c4c076a04aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_application_grant_ngo', ['grant_id', 'ngo_org_id'])

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('total_funding',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.alter_column('total_funding',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_application_grant_ngo', type_='unique')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
