"""add 13 production indexes for scalability

Revision ID: c4c076a04aeb
Revises: 
Create Date: 2026-03-04 08:22:23.312548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c076a04aeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_grant_status', ['grant_id', 'status'], unique=False)
        batch_op.create_index('ix_applications_ngo_status', ['ngo_org_id', 'status'], unique=False)

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_org_date', ['org_id', 'checked_at'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_stored_filename', ['stored_filename'], unique=False)

    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.create_index('ix_grants_donor_status', ['donor_org_id', 'status'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ix_orgs_type', ['org_type'], unique=False)
        batch_op.create_index('ix_orgs_verified', ['verified'], unique=False)

    with op.batch_alter_table('registration_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registry_check_result', sa.Text(), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_grant_status', ['grant_id', 'status'], unique=False)
        batch_op.create_index('ix_reports_org_status', ['submitted_by_org_id', 'status'], unique=False)
        batch_op.create_index('ix_reports_submitted_by_org', ['submitted_by_org_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_user_status', ['reviewer_user_id', 'status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_org_id', ['org_id'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_org_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_user_status')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_submitted_by_org')
        batch_op.drop_index('ix_reports_org_status')
        batch_op.drop_index('ix_reports_grant_status')

    with op.batch_alter_table('registration_verifications', schema=None) as batch_op:
        batch_op.drop_column('registry_check_result')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ix_orgs_verified')
        batch_op.drop_index('ix_orgs_type')

    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.drop_index('ix_grants_donor_status')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_stored_filename')

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_org_date')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_ngo_status')
        batch_op.drop_index('ix_applications_grant_status')

    # ### end Alembic commands ###
